app = 'groupher-status'
primary_region = 'sin'
kill_signal = 'SIGINT'

[build]
  dockerfile = 'Dockerfile'

[env]
  GATUS_CONFIG_PATH = '/config/config.yaml'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  path = '/health'
  protocol = 'http'
  timeout = '5s'

[[mounts]]
  source = 'gatus_data'
  destination = '/data'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
