export const SIDE_TREE_SPACING = {
  VIEWPORT_GUTTER: '-ml-7 pl-7 pr-6',
  TREE_SECTION_GAP: 'gap-y-4',
  TOP_LEVEL_GROUP_GAP: 'gap-y-4',
  NODE_GAP: 'gap-y-1.5',

  TOP_LEVEL_GROUP_MARGIN_TOP: '-mt-0.5',
  TOP_LEVEL_GROUP_COLLAPSED_MARGIN_BOTTOM: '-mb-2',
  TOP_LEVEL_GROUP_HEADER_GUTTER: '-ml-7 pl-8',
  NESTED_GROUP_HEADER_INDENT: 'pl-2',
  NESTED_GROUP_LEVEL_MARGIN_LEFT: 'ml-2',
  TOP_LEVEL_GROUP_CONTENT_GAP: 'mt-2',
  NESTED_GROUP_CONTENT_GAP: 'mt-1.5',

  ITEM_MARKER_GAP: 'mr-2',
  TOP_LEVEL_LEAF_GUTTER: '-ml-7 pl-7',
  NESTED_LEAF_INDENT: 'pl-2.5',
} as const
