defmodule GroupherServer.CMS.Communities.ErrorCat do
  @moduledoc false

  use GroupherServer.ErrorCat.Domain, namespace: {:cms, :community}

  error(:invalid_domain_tag, code: 5506)
  error(:community_root_only, code: 5501)
  error(:passport_community_not_match, code: 5502)
  error(:one_community_only, code: 5503)
  error(:not_exist, code: 5504)
  error(:not_configured, code: 5507)
  error(:application_not_found, code: 5508)
  error(:review_permission_denied, code: 5509)
  error(:asset_not_ready, code: 5510)
  error(:invalid_application_input, code: 5511)
  error(:idempotency_conflict, code: 5512)
  error(:active_application_exists, code: 5513)
  error(:slug_claimed, code: 5514)
  error(:application_state_conflict, code: 5515)
  error(:invalid_passport_shape, code: 5516)
  error(:reserved_slug, code: 5517)
  error(:slug_disputed, code: 5518)
  error(:slug_in_cooldown, code: 5519)
  error(:invalid_slug, code: 5520)
  error(:forbidden, code: 5521)
  error(:community_not_persisted, code: 5522)
  error(:dashboard_not_found, code: 5523)
  error(:asset_not_found, code: 5524)
  error(:asset_not_owned, code: 5525)
  error(:invalid_operation_ref, code: 5526)
  error(:lifecycle_state_conflict, code: 5527)
  error(:archive_recovery_window_expired, code: 5528)
  error(:destroy_blocked, code: 5529)
  error(:invalid_dsb_section, code: 5530)
  error(:missing_lifecycle_audit_action, code: 5531)
  error(:blocker_not_found, code: 5532)
  error(:archive_recovery_window_active, code: 5533)
  error(:lifecycle_not_found, code: 5534)
  error(:apply_not_allowed, code: 5535)
end
