defmodule GroupherServer.CMS.DocImport.Adapters.Docusaurus do
  @moduledoc """
  Reads a Docusaurus docs plugin sidebar into a source navigation tree.

      sidebars.ts                         docs/
      -----------                         -----
      tutorialSidebar: [                  intro.md
        "intro",                         guide/
        {type: "category", ...},    +     _category_.json
        {type: "autogenerated", ...}      start.md
      ]
             |
             v
      SourceTree scope/section/page/link

  Explicit `doc`, `category` and `link` items are supported together with
  `autogenerated` directories. Repository JavaScript is never executed.
  """

  @behaviour GroupherServer.CMS.DocImport.Adapter

  alias GroupherServer.CMS.DocImport.{Diagnostic, DocumentFile, SourceTree, StaticConfig}

  @config_names ~w(docusaurus.config.ts docusaurus.config.js docusaurus.config.mts docusaurus.config.mjs)
  @sidebar_names ~w(sidebars.ts sidebars.js sidebars.mts sidebars.mjs)

  @impl true
  def parse(project_root) do
    with {:ok, site_root, config_path} <- find_site(project_root),
         {:ok, sidebar_path} <- find_sidebar(site_root),
         {:ok, sidebar} <- read_sidebar(sidebar_path) do
      docs_root =
        project_root
        |> relative(site_root)
        |> Path.join("docs")
        |> String.trim_leading("./")

      navigation =
        sidebar
        |> ordered_entries()
        |> Enum.map(fn {name, items} ->
          SourceTree.scope(
            "sidebar:#{name}",
            DocumentFile.humanize(name),
            "/",
            nodes(List.wrap(items), project_root, docs_root, ".")
          )
        end)

      diagnostics = missing_page_diagnostics(sidebar, project_root, docs_root)

      {:ok,
       %{
         tree:
           SourceTree.new(
             :docusaurus,
             docs_root,
             [relative(project_root, config_path), relative(project_root, sidebar_path)],
             navigation
           ),
         diagnostics: diagnostics
       }}
    else
      {:error, :config_not_found} ->
        Diagnostic.error_result("config_not_found", "Docusaurus config was not found")

      {:error, :sidebar_not_found} ->
        Diagnostic.error_result("sidebar_not_found", "Docusaurus sidebars file was not found")

      {:error, _reason} ->
        Diagnostic.error_result(
          "dynamic_config",
          "Docusaurus sidebar is dynamic and cannot be parsed safely"
        )
    end
  end

  defp find_site(root) do
    [root | Path.wildcard(Path.join(root, "*"))]
    |> Enum.flat_map(fn site_root ->
      Enum.map(@config_names, &{site_root, Path.join(site_root, &1)})
    end)
    |> Enum.find_value({:error, :config_not_found}, fn {site_root, path} ->
      if File.regular?(path), do: {:ok, site_root, path}
    end)
  end

  defp find_sidebar(site_root) do
    Enum.find_value(@sidebar_names, {:error, :sidebar_not_found}, fn name ->
      path = Path.join(site_root, name)
      if File.regular?(path), do: {:ok, path}
    end)
  end

  defp read_sidebar(path) do
    case StaticConfig.read(path, "const sidebars") do
      {:ok, sidebar} -> {:ok, sidebar}
      {:error, _reason} -> StaticConfig.read(path, "export default")
    end
  end

  defp nodes(items, project_root, docs_root, dir_name) do
    Enum.flat_map(items, &node(&1, project_root, docs_root, dir_name))
  end

  defp node(id, project_root, docs_root, _dir_name) when is_binary(id),
    do: page(id, nil, project_root, docs_root)

  defp node(%{"type" => "doc", "id" => id} = item, project_root, docs_root, _dir_name),
    do: page(id, Map.get(item, "label"), project_root, docs_root)

  defp node(%{"type" => "link", "href" => href} = item, _project_root, _docs_root, _dir_name),
    do: [SourceTree.link("external:#{href}", Map.get(item, "label", href), href)]

  defp node(%{"type" => "category", "label" => label} = item, project_root, docs_root, dir_name) do
    landing = category_landing(Map.get(item, "link"), project_root, docs_root)
    children = landing ++ nodes(Map.get(item, "items", []), project_root, docs_root, dir_name)
    [SourceTree.section("category:#{SourceTree.slug(label)}", label, children)]
  end

  defp node(%{"type" => "autogenerated"} = item, project_root, docs_root, _dir_name) do
    auto_nodes(project_root, docs_root, Map.get(item, "dirName", "."))
  end

  defp node(_, _project_root, _docs_root, _dir_name), do: []

  defp category_landing(%{"type" => "doc", "id" => id} = link, project_root, docs_root),
    do: page(id, Map.get(link, "label"), project_root, docs_root)

  defp category_landing(_link, _project_root, _docs_root), do: []

  defp page(id, label, project_root, docs_root) do
    absolute_root = Path.join(project_root, docs_root)

    case DocumentFile.resolve(absolute_root, id) do
      nil ->
        []

      path ->
        source_path = Path.relative_to(path, project_root)
        metadata = doc_metadata(path, id)
        title = label || metadata.title
        [SourceTree.page(source_path, title, doc_route(id, metadata.slug), source_path)]
    end
  end

  defp auto_nodes(project_root, docs_root, dir_name) do
    absolute = Path.join([project_root, docs_root, dir_name])

    entries =
      absolute
      |> DocumentFile.entries()
      |> Enum.map(&auto_entry(&1, project_root, docs_root, dir_name))
      |> Enum.reject(&is_nil/1)
      |> Enum.sort_by(fn {position, title, _node} -> {position, title} end)

    Enum.map(entries, &elem(&1, 2))
  end

  defp auto_entry(%{kind: :directory, name: name, path: path}, project_root, docs_root, dir_name) do
    category = category_metadata(path, name)
    child_dir = Path.join(dir_name, name)
    children = auto_nodes(project_root, docs_root, child_dir)
    node = SourceTree.section("category:#{child_dir}", category.title, children)
    {category.position, category.title, node}
  end

  defp auto_entry(%{kind: :file, name: name, path: path}, project_root, _docs_root, dir_name) do
    id = Path.join(dir_name, Path.rootname(name)) |> String.trim_leading("./")
    metadata = doc_metadata(path, id)

    node =
      SourceTree.page(
        relative(project_root, path),
        metadata.title,
        doc_route(id, metadata.slug),
        relative(project_root, path)
      )

    {metadata.position, metadata.title, node}
  end

  defp category_metadata(path, fallback) do
    json_path = Path.join(path, "_category_.json")

    with {:ok, body} <- File.read(json_path),
         {:ok, data} <- Jason.decode(body) do
      %{
        title: Map.get(data, "label", DocumentFile.humanize(fallback)),
        position: Map.get(data, "position", 999_999)
      }
    else
      _ -> %{title: DocumentFile.humanize(fallback), position: 999_999}
    end
  end

  defp doc_metadata(path, fallback) do
    frontmatter = DocumentFile.frontmatter(path)

    %{
      title: DocumentFile.title(path, fallback, ["sidebar_label", "title"]),
      position: DocumentFile.integer(frontmatter, "sidebar_position"),
      slug: Map.get(frontmatter, "slug")
    }
  end

  defp doc_route(id, slug) when is_binary(slug) do
    if String.starts_with?(slug, "/") do
      slug
    else
      ("/" <> Path.join(Path.dirname(id), slug)) |> String.replace("/./", "/")
    end
  end

  defp doc_route(id, _slug), do: "/" <> String.trim_leading(id, "/")

  defp missing_page_diagnostics(sidebar, project_root, docs_root) do
    absolute_root = Path.join(project_root, docs_root)

    sidebar
    |> sidebar_doc_ids()
    |> Enum.uniq()
    |> Enum.reject(&DocumentFile.resolve(absolute_root, &1))
    |> Enum.map(fn id ->
      Diagnostic.warning("page_not_found", "Docusaurus sidebar page was not found",
        source_id: id,
        file: docs_root
      )
    end)
  end

  defp sidebar_doc_ids(value) when is_binary(value), do: [value]
  defp sidebar_doc_ids(value) when is_list(value), do: Enum.flat_map(value, &sidebar_doc_ids/1)

  defp sidebar_doc_ids(%{"type" => "doc", "id" => id}), do: [id]
  defp sidebar_doc_ids(%{"type" => type}) when type in ["link", "autogenerated"], do: []

  defp sidebar_doc_ids(%{"type" => "category"} = item) do
    landing =
      case Map.get(item, "link") do
        %{"type" => "doc", "id" => id} -> [id]
        _ -> []
      end

    landing ++ sidebar_doc_ids(Map.get(item, "items", []))
  end

  defp sidebar_doc_ids(%{"__order__" => order} = sidebar),
    do: Enum.flat_map(order, &sidebar_doc_ids(Map.fetch!(sidebar, &1)))

  defp sidebar_doc_ids(_value), do: []

  defp ordered_entries(%{"__order__" => order} = map),
    do: Enum.map(order, &{&1, Map.fetch!(map, &1)})

  defp ordered_entries(map), do: Enum.sort_by(map, fn {key, _value} -> key end)

  defp relative(root, path), do: Path.relative_to(path, root)
end
