/*
 * this is only for the twBelt hook type hints
 */

export default {
  transparent: '',
  primary: '',
  container: '',
  cardAlpha: '',
  card: '',
  loading: {
    basic: '',
    animate: '',
  },
  error: {
    title: '',
    desc: '',
    bg: '',
  },
  font: '',
  link: '',
  blackActive: '',
  divider: '',
  alphaBg: '',
  alphaBg2: '',
  sandBox: '',
  hoverBg: '',
  hoverActive: '',
  menuHoverBg: '',
  lineDivider: '',
  hoverBorder: '',
  linkHover: '',
  heightIcon: '',
  heightGradient: '',
  bodyBg: '',
  textBadge: '',
  lightText: '',
  hint: '',
  articleCardShadow: '',
  articleCardHover: '',
  dashboardBlockOpacity: '',
  snackBar: '',
  rainbow: {
    red: '',
    redSoft: '',
    orange: '',
    orangeSoft: '',
    brown: '',
    brownSoft: '',
    yellow: '',
    yellowSoft: '',
    green: '',
    greenSoft: '',
    greenLight: '',
    greenLightSoft: '',
    cyan: '',
    cyanSoft: '',
    cyanLight: '',
    cyanLightSoft: '',
    blue: '',
    blueSoft: '',
    purple: '',
    purpleSoft: '',
    pink: '',
    pinkSoft: '',
    black: '',
    blackBtn: '',
    blackSoft: '',
  },
  shadow: {
    md: '',
    lg: '',
    xl: '',
    xxl: '',
  },
  gradientBg: {
    purple: '',
    blue: '',
    green: '',
    orange: '',
    pink: '',
    black: '',
    cyan: '',
    yellow: '',
  },
  text: {
    title: '',
    digest: '',
    body: '',
    hint: '',
    invert: '',
    link: '',
  },
  dot: '',
  article: {
    title: '',
    digest: '',
    info: '',
    link: '',
  },
  content: {
    bg: '',
  },
  footer: {
    text: '',
    hover: '',
    title: '',
    bottomBg: '',
    shadow: '',
  },
  drawer: {
    mask: '',
    bg: '',
    shadow: '',
    shadowLite: '',
    closerShadow: '',
    border: '',
  },
  comment: {
    bg: '',
    icon: '',
    didIcon: '',
    title: '',
    username: '',
    number: '',
    floor: '',
    reply: '',
    replyBg: '',
    placeholder: '',
    filter: '',
    filterActive: '',
    action: '',
    mentionText: '',
    mentionTextBg: '',
    mentionBg: '',
    mentionBorder: '',
    indentLine: '',
    indentActive: '',
  },
  editor: {
    title: '',
    content: '',
    placeholder: '',
    contentBg: '',
    border: '',
    borderActive: '',
    borderNormal: '',
    footer: '',
  },
  code: {
    bg: '',
  },
  button: {
    primary: '',
    toggle: '',
    redBg: '',
    fg: '',
    blackFg: '',
    hoverBg: '',
    upvoteBorder: '',
  },
  navigator: {
    activeBottom: '',
    borderRight: '',
    hoverBg: '',
  },
  notice: {
    bg: '',
    icon: '',
  },
  popover: {
    bg: '',
    borderColor: '',
    boxShadow: '',
    activeBorder: '',
  },
  tags: {
    text: '',
  },
  tagger: {
    text: '',
    bg: '',
    border: '',
    closeBtn: '',
  },
  tabs: {
    headerActive: '',
    header: '',
    contentBg: '',
    headerBg: '',
    headerActiveTop: '',
    border: '',
    bottomLine: '',
  },
  modal: {
    bg: '',
    mask: '',
    border: '',
    shadow: '',
    innerSelectBg: '',
    subPanel: '',
  },
  form: {
    inputBg: '',
    text: '',
    label: '',
    border: '',
    shadow: '',
  },
  a: {
    hover: '',
    active: '',
  },
  toast: {
    bg: '',
    border: '',
    title: '',
  },
  table: {
    headerBg: '',
    headTitle: '',
    text: '',
    border: '',
    hoverBg: '',
  },
  avatar: {
    opacity: '',
    quote: '',
    shadow: '',
  },
  dashboard: {
    menuCat: '',
    menuTitle: '',
    blockActiveBg: '',
  },
  toggle: {
    shadow: '',
    ball: '',
  },
  hiddenPanel: '',
}
