defmodule GroupherServer.CMS.DocTree.Publish do
  @moduledoc """
  Publish workflows for docs and docs tree snapshots.

      Dashboard Editor
      ├─ Doc draft changes
      │    docs(stage=draft)
      │
      └─ Tree draft changes
           doc_tree_events(owner=tree, status=staged)

                 |
                 v
          publish_changes/3
                 |
                 ├─ docs + DocDocument
                 ├─ doc_tree_nodes(stage=public)
                 └─ publish_releases
                      ├─ tree_snapshot_id -> doc_tree_snapshots
                      ├─ publish_release_articles
                      └─ publish_release_tree_events

  Tree and article are still separate domains internally, but the public product
  surface exposes one publish action. The release row is the snapshot anchor that
  lets history and rollback talk about the full public docs site at one moment.
  """

  import Ecto.Query, warn: false

  alias GroupherServer.{Accounts, CMS, Repo}
  alias Accounts.Model.User
  alias CMS.DocTree.Events

  require CMS.Const

  alias CMS.Model.{
    ArticleSnapshot,
    Community,
    Doc,
    DocTreeEvent,
    DocTreeNode,
    DocsSiteState,
    PublishRelease,
    PublishReleaseArticle,
    PublishReleaseTreeEvent
  }

  alias Helper.{ORM, T, Transaction}

  @event_public_fields %{
    "title" => :title,
    "slug" => :slug,
    "href" => :href,
    "marker" => :marker,
    "badge" => :badge,
    "hidden" => :hidden,
    "uiConfig" => :ui_config,
    "ui_config" => :ui_config
  }

  @doc """
  Builds the unified publish checklist consumed by the editor ActionSnackbar.

  The returned ids are opaque UI ids. The frontend should show them as a simple
  checklist and send selected ids back to `publish_changes/4`; dependency
  resolution stays server-side.

  ## Examples

      iex> Publish.scope(community).total_count
      3
  """
  @spec scope(Community.t()) :: map()
  def scope(%Community{} = community) do
    doc_changes = doc_change_items(community)
    tree_changes = tree_change_items(community)

    %{
      total_count: length(doc_changes) + length(tree_changes),
      doc_changes: doc_changes,
      tree_changes: tree_changes
    }
  end

  @doc """
  Publishes selected doc and tree changes as a single release.

  Nil selections mean "publish every selected-by-default item" from the current
  scope. Explicit lists publish only those opaque scope item ids.

  ## Examples

      iex> Publish.publish_changes(community, %{doc_change_ids: ["doc:12"]}, user)
      {:ok, %{done: true, release: %PublishRelease{}}}
  """
  @spec publish_changes(Community.t(), map(), User.t(), keyword()) :: T.domain_res(map())
  def publish_changes(%Community{} = community, args, %User{} = user, opts \\ []) do
    sync_cover? = Keyword.get(opts, :sync_cover, true)

    Transaction.lock_global("doc_tree:#{community.id}", fn ->
      Repo.transaction(fn ->
        current_scope = scope(community)

        with {:ok, doc_ids} <- selected_ids(args, :doc_change_ids, current_scope.doc_changes),
             {:ok, tree_ids} <- selected_ids(args, :tree_change_ids, current_scope.tree_changes),
             {:ok, tree_result} <- prepare_tree_scope_items(community, tree_ids),
             :ok <- preapply_tree_delete_events(community, tree_result.events),
             {:ok, doc_revisions} <-
               publish_doc_scope_items(
                 community,
                 current_scope.doc_changes,
                 doc_ids,
                 user,
                 sync_cover?
               ),
             :ok <- apply_tree_events_to_public(community, tree_result.events),
             {:ok, release} <- create_release(community, user, doc_revisions, tree_result),
             next_scope <- scope(community),
             {:ok, _state} <- mark_site_release_published(community, user, next_scope) do
          %{done: true, release: release, scope: next_scope}
        else
          {:error, reason} -> Repo.rollback(reason)
          reason -> Repo.rollback(reason)
        end
      end)
      |> case do
        {:ok, result} -> {:ok, result}
        {:error, reason} -> {:error, reason}
      end
    end)
  end

  @doc """
  Moves a published doc page back to draft by creating a new draft row sharing
  the same `doc_id`. The public row is left untouched — it stays served until
  the next publish overwrites it.

  Content is copied from the public `DocDocument` JSON body and flows through
  `Articles.Draft.create` so all derived fields (markdown, html, content_hash,
  etc.) are regenerated by ContentPipeline. The caller's `user` is recorded as
  the draft author for audit.

  ## Examples

      iex> Publish.move_doc_to_draft(community, draft_node.node_id, user)
      {:ok, %Doc{stage: CMS.Const.stage(:draft), doc_id: "a1b2c3d4-..."}}
  """
  @spec move_doc_to_draft(Community.t(), T.id(), User.t()) :: T.domain_res(Doc.t())
  def move_doc_to_draft(%Community{} = community, node_id, %User{} = user) do
    alias CMS.Articles.Draft

    with {:ok, draft_node} <- find_draft_node(community, node_id),
         {:ok, public_doc} <-
           ORM.find_by(Doc,
             community_id: community.id,
             doc_id: draft_node.doc_id,
             stage: CMS.Const.stage(:public)
           ),
         {:ok, document} <-
           ORM.find_by(CMS.Model.DocDocument, doc_id: public_doc.id) do
      case Draft.read(community, public_doc.doc_id) do
        {:ok, draft} ->
          {:ok, draft}

        {:error, _} ->
          Draft.create(
            community,
            :doc,
            %{
              doc_id: public_doc.doc_id,
              title: public_doc.title,
              slug: public_doc.slug,
              body: document.json
            },
            user
          )
      end
    end
  end

  defp find_draft_node(%Community{} = community, node_id) do
    node_id = to_string(node_id)

    DocTreeNode
    |> where(
      [node],
      node.community_id == ^community.id and node.stage == CMS.Const.stage(:draft) and
        (node.node_id == ^node_id or fragment("?::text", node.id) == ^node_id)
    )
    |> limit(1)
    |> Repo.one()
    |> case do
      %DocTreeNode{} = node -> {:ok, node}
      nil -> {:error, {:custom, "Doc tree node(draft) not found"}}
    end
  end

  @doc """
  Deprecated by the stage model; tree draft/public state is owned by tree events.
  """
  @spec move_group_to_draft(Community.t(), T.id()) :: T.domain_res(map())
  def move_group_to_draft(_community, _group_id), do: {:ok, %{done: true}}

  @doc """
  Resolves the public-stage node for a stable draft `node_id`.

  Cover mutations use this to translate editor ids into public tree rows.

  ## Examples

      iex> Publish.public_node_for_draft(community, draft.node_id)
      {:ok, %DocTreeNode{stage: CMS.Const.stage(:public)}}
  """
  @spec public_node_for_draft(Community.t(), T.id()) :: T.domain_res(DocTreeNode.t())
  def public_node_for_draft(%Community{} = community, node_id) do
    ORM.find_by(DocTreeNode,
      community_id: community.id,
      stage: CMS.Const.stage(:public),
      node_id: to_string(node_id)
    )
  end

  defp publish_doc_draft(
         %Community{} = community,
         %{doc_id: doc_id, page_node_id: page_node_id},
         %User{} = user,
         sync_cover?
       ) do
    with {:ok, page} <- find_publish_page(community, doc_id, page_node_id),
         {:ok, group} <- find_publish_group(community, page.group_id, page.stage),
         {:ok, snapshot} <- CMS.Articles.publish_doc_draft(community, doc_id, user),
         {:ok, public_group} <- upsert_public_node(community, group),
         {:ok, public_page} <-
           upsert_public_node(
             community,
             page,
             public_group.node_id,
             snapshot.doc_id
           ),
         {:ok, _sync} <- maybe_sync_cover(community, public_group, public_page, sync_cover?) do
      Events.mark_doc_bound_published(community, doc_id)
      Events.mark_tree_create_published(community, [group.node_id])
      {:ok, snapshot}
    end
  end

  defp selected_ids(args, key, items) do
    case Map.get(args, key) || Map.get(args, Atom.to_string(key)) do
      nil ->
        {:ok, items |> Enum.filter(& &1.selectable) |> Enum.map(& &1.id)}

      ids when is_list(ids) ->
        by_id = Map.new(items, &{&1.id, &1})

        ids
        |> Enum.map(&to_string/1)
        |> Enum.reduce_while({:ok, []}, fn id, {:ok, acc} ->
          case Map.get(by_id, id) do
            nil ->
              {:halt, {:error, {:custom, "Selected publish item no longer exists."}}}

            %{selectable: false, disabled_reason: reason} ->
              {:halt, {:error, {:custom, reason || "Selected publish item is not available."}}}

            _item ->
              {:cont, {:ok, [id | acc]}}
          end
        end)
        |> case do
          {:ok, selected} -> {:ok, Enum.reverse(selected)}
          error -> error
        end
    end
  end

  defp publish_doc_scope_items(
         %Community{} = community,
         scope_items,
         doc_ids,
         %User{} = user,
         sync_cover?
       ) do
    items = Map.new(scope_items, &{&1.id, &1})

    doc_ids
    |> Enum.reduce_while({:ok, []}, fn id, {:ok, acc} ->
      with %{doc_id: _doc_id} = item <- Map.get(items, id),
           {:ok, snapshot} <-
             publish_doc_draft(
               community,
               item,
               user,
               sync_cover?
             ) do
        {:cont, {:ok, [%{snapshot: snapshot, scope_item: item} | acc]}}
      else
        nil -> {:halt, {:error, {:custom, "Selected docs publish item no longer exists."}}}
        error -> {:halt, error}
      end
    end)
    |> case do
      {:ok, entries} -> {:ok, Enum.reverse(entries)}
      error -> error
    end
  end

  defp prepare_tree_scope_items(%Community{} = community, tree_ids) do
    events = selected_tree_events(community, tree_ids)

    if length(events) != length(tree_ids) do
      {:error, {:custom, "Selected tree publish item no longer exists."}}
    else
      article_snapshots = release_article_snapshots_before_tree_events(community, events)

      {:ok, %{events: events, article_snapshots: article_snapshots}}
    end
  end

  defp preapply_tree_delete_events(%Community{} = community, events) do
    events
    |> Enum.filter(&(&1.event_type == CMS.Const.doc_tree_action(:node_delete)))
    |> apply_tree_events_to_public(community)
  end

  defp apply_tree_events_to_public(events, %Community{} = community),
    do: apply_tree_events_to_public(community, events)

  defp apply_tree_events_to_public(%Community{} = community, events) do
    events
    |> Enum.reduce_while(:ok, fn event, :ok ->
      case apply_tree_event_to_public(community, event) do
        :ok -> {:cont, :ok}
        {:ok, _node} -> {:cont, :ok}
        error -> {:halt, error}
      end
    end)
  end

  defp selected_tree_events(_community, []), do: []

  defp selected_tree_events(%Community{} = community, tree_ids) do
    ids =
      tree_ids
      |> Enum.map(&String.replace_prefix(&1, "tree:", ""))
      |> Enum.map(&String.to_integer/1)

    DocTreeEvent
    |> where([e], e.community_id == ^community.id)
    |> where([e], e.status == CMS.Const.doc_tree_event_status(:staged))
    |> where([e], e.owner == CMS.Const.doc_tree_action_owner(:tree))
    |> where([e], e.id in ^ids)
    |> order_by([e], asc: e.seq, asc: e.id)
    |> Repo.all()
  end

  defp apply_tree_event_to_public(
         %Community{} = community,
         %DocTreeEvent{event_type: CMS.Const.doc_tree_action(:node_create)} = event
       ) do
    node = event.payload["node"] || %{}

    with {:ok, attrs} <- public_attrs_from_event_node(community, node) do
      upsert_public_node_attrs(community, node["id"], attrs)
    end
  end

  defp apply_tree_event_to_public(
         %Community{} = community,
         %DocTreeEvent{event_type: CMS.Const.doc_tree_action(:node_delete)} = event
       ) do
    node = event.payload["node"] || %{}

    delete_public_node_by_node_id(community, node["id"])
  end

  defp apply_tree_event_to_public(
         %Community{} = community,
         %DocTreeEvent{event_type: CMS.Const.doc_tree_action(:node_move)} = event
       ) do
    payload = event.payload

    update_public_node_by_node_id(community, payload["nodeId"], %{
      group_id: payload["afterGroupId"],
      index: payload["afterIndex"]
    })
  end

  defp apply_tree_event_to_public(%Community{} = community, %DocTreeEvent{} = event) do
    payload = event.payload

    with {:ok, field} <- field_atom(payload["field"]) do
      update_public_node_by_node_id(community, payload["nodeId"], %{field => payload["after"]})
    end
  end

  defp public_attrs_from_event_node(%Community{} = community, %{"type" => "page"} = node) do
    doc_id = node["docId"]

    with {:ok, _draft} <-
           ORM.find_by(Doc,
             doc_id: doc_id,
             stage: CMS.Const.stage(:draft),
             community_id: community.id
           ) do
      {:ok,
       %{
         community_id: community.id,
         node_id: node["id"],
         stage: CMS.Const.stage(:public),
         type: :page,
         group_id: node["groupId"],
         doc_id: doc_id,
         title: node["title"],
         slug: node["slug"],
         index: node["index"] || 0,
         href: node["href"],
         marker: node["marker"],
         badge: node["badge"],
         hidden: Map.get(node, "hidden", false),
         ui_config: Map.get(node, "uiConfig", %{})
       }}
    else
      {:error, _} -> {:error, {:custom, "Publish docs before publishing tree."}}
      error -> error
    end
  end

  defp public_attrs_from_event_node(%Community{} = community, node) do
    {:ok,
     %{
       community_id: community.id,
       node_id: node["id"],
       stage: CMS.Const.stage(:public),
       type: String.to_existing_atom(node["type"]),
       group_id: node["groupId"],
       doc_id: nil,
       title: node["title"],
       slug: node["slug"],
       index: node["index"] || 0,
       href: node["href"],
       marker: node["marker"],
       badge: node["badge"],
       hidden: Map.get(node, "hidden", false),
       ui_config: Map.get(node, "uiConfig", %{})
     }}
  end

  defp upsert_public_node_attrs(%Community{} = community, node_id, attrs) do
    case public_node_by_identity(community, node_id, attrs) do
      %DocTreeNode{} = node -> ORM.update(node, attrs)
      nil -> ORM.create(DocTreeNode, attrs)
    end
  end

  defp update_public_node_by_node_id(%Community{} = community, node_id, attrs) do
    case public_node_by_node_id(community, node_id) do
      %DocTreeNode{} = node -> ORM.update(node, attrs)
      nil -> {:ok, :missing}
    end
  end

  defp delete_public_node_by_node_id(%Community{} = community, node_id) do
    case public_node_by_node_id(community, node_id) do
      %DocTreeNode{type: :group} = node ->
        delete_public_group_children(community, node.node_id)

        ORM.delete(node)

      %DocTreeNode{} = node ->
        ORM.delete(node)

      nil ->
        delete_public_group_children(community, node_id)
    end
  end

  defp delete_public_group_children(%Community{} = community, group_id) do
    community
    |> public_group_children(group_id)
    |> Enum.each(&ORM.delete/1)

    :ok
  end

  defp public_node_by_node_id(%Community{} = community, node_id) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == CMS.Const.stage(:public))
    |> where([n], n.node_id == ^to_string(node_id))
    |> Repo.one()
  end

  defp public_group_children(%Community{} = community, group_id) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == CMS.Const.stage(:public))
    |> where([n], n.group_id == ^group_id)
    |> Repo.all()
  end

  defp field_atom(field) do
    case Map.fetch(@event_public_fields, field) do
      {:ok, atom} -> {:ok, atom}
      :error -> {:error, {:custom, "Unsupported docs tree field: #{field}"}}
    end
  end

  defp create_release(
         %Community{} = community,
         %User{} = user,
         doc_entries,
         %{events: tree_events, article_snapshots: article_snapshots}
       ) do
    tree_json = CMS.DocTree.Snapshot.published_json(community)
    event_ids = Enum.map(tree_events, & &1.id)

    with {:ok, tree_snapshot} <-
           Events.publish_snapshot(community, user.id, "publish release",
             tree_json: tree_json,
             event_ids: event_ids
           ),
         {:ok, _state} <- mark_tree_release_published(community, tree_snapshot),
         {:ok, release} <-
           ORM.create(PublishRelease, %{
             community_id: community.id,
             release_number: next_release_number(community),
             tree_snapshot_id: tree_snapshot.id,
             author_id: user.id,
             published_at: DateTime.utc_now(:second)
           }),
         {:ok, _articles} <-
           create_release_articles(release, doc_entries, tree_events, article_snapshots),
         {:ok, _events} <- create_release_tree_events(release, tree_events) do
      {:ok, release}
    end
  end

  defp mark_tree_release_published(%Community{} = community, tree_snapshot) do
    with {:ok, state} <- ORM.find_by(DocsSiteState, community_id: community.id) do
      ORM.update(state, %{
        base_snapshot_id: tree_snapshot.id,
        staged_event_count: Events.staged_tree_event_count(community)
      })
    end
  end

  defp mark_site_release_published(%Community{} = community, %User{} = user, next_scope) do
    with {:ok, state} <- ORM.find_by(DocsSiteState, community_id: community.id) do
      attrs = %{
        last_published_at: DateTime.utc_now(:second),
        last_published_by_id: user.id
      }

      attrs =
        if next_scope.total_count == 0 do
          Map.put(attrs, :published_version, state.site_draft_version)
        else
          attrs
        end

      ORM.update(state, attrs)
    end
  end

  defp create_release_articles(
         %PublishRelease{} = release,
         doc_entries,
         tree_events,
         article_snapshots
       ) do
    doc_rows = Enum.map(doc_entries, &release_article_attrs_from_doc(release, &1))

    tree_rows = release_article_attrs_from_tree_events(release, tree_events, article_snapshots)

    (doc_rows ++ tree_rows)
    |> Enum.reject(&is_nil/1)
    |> merge_release_article_attrs()
    |> Enum.reduce_while({:ok, []}, fn attrs, {:ok, acc} ->
      case ORM.create(PublishReleaseArticle, attrs) do
        {:ok, row} -> {:cont, {:ok, [row | acc]}}
        error -> {:halt, error}
      end
    end)
    |> case do
      {:ok, rows} -> {:ok, Enum.reverse(rows)}
      error -> error
    end
  end

  defp release_article_attrs_from_doc(%PublishRelease{} = release, %{
         snapshot: %ArticleSnapshot{} = snapshot,
         scope_item: scope_item
       }) do
    node = public_page_by_doc_id(release.community_id, snapshot.doc_id)

    %{
      release_id: release.id,
      doc_id: snapshot.doc_id,
      snapshot_id: snapshot.id,
      node_id: node && node.node_id,
      group_node_id: node && node.group_id,
      index: node && node.index,
      title: snapshot.title,
      actions: [scope_item.action]
    }
  end

  defp release_article_attrs_from_tree_events(
         %PublishRelease{} = release,
         tree_events,
         article_snapshots
       ) do
    snapshot_rows =
      article_snapshots
      |> Map.values()
      |> Enum.map(&Map.put(&1, :release_id, release.id))

    current_rows =
      tree_events
      |> Enum.flat_map(&article_node_ids_from_tree_event/1)
      |> Enum.uniq()
      |> Enum.map(fn node_id ->
        with %DocTreeNode{doc_id: doc_id} = node when not is_nil(doc_id) <-
               public_page_by_node_id(release.community_id, node_id),
             %ArticleSnapshot{} = snapshot <-
               latest_public_article_snapshot(release.community_id, doc_id) do
          %{
            release_id: release.id,
            doc_id: doc_id,
            snapshot_id: snapshot.id,
            node_id: node.node_id,
            group_node_id: node.group_id,
            index: node.index,
            title: snapshot.title,
            actions: actions_from_tree_events(tree_events, node.node_id)
          }
        else
          _ -> nil
        end
      end)

    snapshot_rows ++ current_rows
  end

  defp release_article_snapshots_before_tree_events(%Community{} = community, tree_events) do
    tree_events
    |> Enum.flat_map(&release_article_snapshots_before_tree_event(community, &1))
    |> Enum.reject(&is_nil/1)
    |> merge_release_article_attrs()
    |> Map.new(&{&1.node_id, Map.delete(&1, :release_id)})
  end

  defp release_article_snapshots_before_tree_event(
         %Community{} = community,
         %DocTreeEvent{
           event_type: CMS.Const.doc_tree_action(:node_delete),
           payload: %{"node" => %{"type" => "group", "id" => id}}
         } = event
       ) do
    community
    |> public_group_children(id)
    |> Enum.filter(&(&1.type == :page))
    |> Enum.map(
      &release_article_attrs_from_public_node(community.id, &1, [tree_event_action(event)])
    )
  end

  defp release_article_snapshots_before_tree_event(
         %Community{} = community,
         %DocTreeEvent{
           event_type: CMS.Const.doc_tree_action(:node_delete),
           payload: %{"node" => %{"type" => "page"}}
         } = event
       ) do
    event
    |> article_node_ids_from_tree_event()
    |> Enum.map(fn node_id ->
      with %DocTreeNode{} = node <- public_page_by_node_id(community.id, node_id) do
        release_article_attrs_from_public_node(community.id, node, [tree_event_action(event)])
      end
    end)
  end

  defp release_article_snapshots_before_tree_event(_community, _event), do: []

  defp release_article_attrs_from_public_node(
         community_id,
         %DocTreeNode{doc_id: doc_id} = node,
         actions
       )
       when not is_nil(doc_id) do
    with %ArticleSnapshot{} = snapshot <- latest_public_article_snapshot(community_id, doc_id) do
      %{
        doc_id: doc_id,
        snapshot_id: snapshot.id,
        node_id: node.node_id,
        group_node_id: node.group_id,
        index: node.index,
        title: snapshot.title,
        actions: actions
      }
    end
  end

  defp release_article_attrs_from_public_node(_community_id, _node, _actions), do: nil

  defp merge_release_article_attrs(rows) do
    rows
    |> Enum.group_by(& &1.doc_id)
    |> Enum.map(fn {_doc_id, grouped_rows} ->
      Enum.reduce(grouped_rows, %{}, fn row, acc ->
        Map.merge(acc, row, fn
          :actions, left, right -> Enum.uniq(left ++ right)
          _key, nil, right -> right
          _key, left, nil -> left
          _key, _left, right -> right
        end)
      end)
    end)
  end

  defp create_release_tree_events(%PublishRelease{} = release, tree_events) do
    tree_events
    |> Enum.reduce_while({:ok, []}, fn event, {:ok, acc} ->
      case ORM.create(PublishReleaseTreeEvent, %{
             release_id: release.id,
             doc_tree_event_id: event.id,
             event_type: event.event_type,
             label: tree_event_label(event),
             payload: event.payload,
             inverse_payload: event.inverse_payload
           }) do
        {:ok, row} -> {:cont, {:ok, [row | acc]}}
        error -> {:halt, error}
      end
    end)
    |> case do
      {:ok, rows} -> {:ok, Enum.reverse(rows)}
      error -> error
    end
  end

  defp public_page_by_doc_id(community_id, doc_id) do
    DocTreeNode
    |> where([n], n.community_id == ^community_id)
    |> where([n], n.stage == CMS.Const.stage(:public))
    |> where([n], n.type == :page)
    |> where([n], n.doc_id == ^doc_id)
    |> Repo.one()
  end

  defp public_page_by_node_id(community_id, node_id) do
    DocTreeNode
    |> where([n], n.community_id == ^community_id)
    |> where([n], n.stage == CMS.Const.stage(:public))
    |> where([n], n.type == :page)
    |> where([n], n.node_id == ^node_id)
    |> Repo.one()
  end

  defp latest_public_article_snapshot(community_id, doc_id) do
    ArticleSnapshot
    |> where([r], r.community_id == ^community_id)
    |> where([r], r.stage == CMS.Const.stage(:public))
    |> where([r], r.article_thread == :doc)
    |> where([r], r.doc_id == ^doc_id)
    |> order_by([r], desc: r.snapshot_number, desc: r.id)
    |> limit(1)
    |> Repo.one()
  end

  defp article_node_ids_from_tree_event(%DocTreeEvent{
         event_type: CMS.Const.doc_tree_action(:node_create),
         payload: %{"node" => %{"type" => "page", "id" => id}}
       }),
       do: [id]

  defp article_node_ids_from_tree_event(%DocTreeEvent{
         event_type: CMS.Const.doc_tree_action(:node_delete),
         payload: %{"node" => %{"type" => "page", "id" => id}}
       }),
       do: [id]

  defp article_node_ids_from_tree_event(%DocTreeEvent{payload: %{"nodeId" => id}}), do: [id]
  defp article_node_ids_from_tree_event(_event), do: []

  defp actions_from_tree_events(tree_events, node_id) do
    tree_events
    |> Enum.filter(&(node_id in article_node_ids_from_tree_event(&1)))
    |> Enum.map(&tree_event_action/1)
    |> Enum.uniq()
  end

  defp next_release_number(%Community{} = community) do
    PublishRelease
    |> where([r], r.community_id == ^community.id)
    |> select([r], max(r.release_number))
    |> Repo.one()
    |> case do
      nil -> 1
      number -> number + 1
    end
  end

  defp doc_change_items(%Community{} = community) do
    drafts =
      Doc
      |> where([d], d.community_id == ^community.id)
      |> where([d], d.stage == CMS.Const.stage(:draft))
      |> order_by([d], asc: d.inserted_at, asc: d.id)
      |> Repo.all()

    drafts_by_doc_id = Map.new(drafts, &{&1.doc_id, &1})
    pages = publish_pages_for_drafts(community, Map.keys(drafts_by_doc_id))
    pages_by_doc_id = Map.new(pages, &{&1.doc_id, &1})

    Enum.map(drafts, fn draft ->
      page = Map.get(pages_by_doc_id, draft.doc_id)
      public = public_article_snapshot(community, draft)
      action = if public, do: "modified", else: "created"
      selectable = not is_nil(page)
      disabled_reason = unless selectable, do: "Doc draft is not attached to a tree page."

      %{
        id: "doc:#{draft.doc_id}",
        doc_id: draft.doc_id,
        page_node_id: page && page.node_id,
        title: draft.title,
        action: action,
        selected_by_default: selectable,
        selectable: selectable,
        disabled_reason: disabled_reason
      }
    end)
  end

  defp tree_change_items(%Community{} = community) do
    community
    |> Events.staged_events(owner: CMS.Const.doc_tree_action_owner(:tree))
    |> Enum.reject(&doc_bound_page_create_event?(community, &1))
    |> Enum.reject(&doc_bound_group_create_event?(community, &1))
    |> Enum.map(fn event ->
      {selectable, disabled_reason} = tree_event_select_state(community, event)

      %{
        id: "tree:#{event.id}",
        event_id: event.id,
        title: tree_event_label(event),
        action: tree_event_action(event),
        selected_by_default: selectable,
        selectable: selectable,
        disabled_reason: disabled_reason
      }
    end)
  end

  defp doc_bound_page_create_event?(
         %Community{} = community,
         %DocTreeEvent{
           event_type: CMS.Const.doc_tree_action(:node_create),
           payload: %{"node" => %{"type" => "page", "docId" => doc_id}}
         }
       ) do
    match?(
      {:ok, %Doc{}},
      ORM.find_by(Doc, community_id: community.id, doc_id: doc_id, stage: CMS.Const.stage(:draft))
    )
  end

  defp doc_bound_page_create_event?(_community, _event), do: false

  defp doc_bound_group_create_event?(
         %Community{} = community,
         %DocTreeEvent{
           event_type: CMS.Const.doc_tree_action(:node_create),
           payload: %{"node" => %{"type" => "group", "id" => group_id}}
         }
       ) do
    draft_doc_ids =
      Doc
      |> where([d], d.community_id == ^community.id)
      |> where([d], d.stage == CMS.Const.stage(:draft))
      |> select([d], d.doc_id)
      |> Repo.all()

    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == CMS.Const.stage(:draft))
    |> where([n], n.type == :page)
    |> where([n], n.group_id == ^group_id)
    |> where([n], n.doc_id in ^draft_doc_ids)
    |> Repo.exists?()
  end

  defp doc_bound_group_create_event?(_community, _event), do: false

  defp tree_event_select_state(
         %Community{} = community,
         %DocTreeEvent{
           event_type: CMS.Const.doc_tree_action(:node_create),
           payload: %{"node" => %{"type" => "page"} = node}
         }
       ) do
    with {:ok, %Doc{community_id: _cid}} <-
           ORM.find_by(Doc,
             doc_id: node["docId"],
             stage: CMS.Const.stage(:draft),
             community_id: community.id
           ) do
      {true, nil}
    else
      _ -> {false, "Publish the page content first."}
    end
  end

  defp tree_event_select_state(_community, _event), do: {true, nil}

  defp public_article_snapshot(%Community{} = community, %Doc{doc_id: doc_id}) do
    ArticleSnapshot
    |> where([s], s.community_id == ^community.id)
    |> where([s], s.stage == CMS.Const.stage(:public))
    |> where([s], s.article_thread == :doc)
    |> where([s], s.doc_id == ^doc_id)
    |> order_by([s], desc: s.snapshot_number, desc: s.id)
    |> limit(1)
    |> Repo.one()
  end

  defp tree_event_action(%DocTreeEvent{event_type: CMS.Const.doc_tree_action(:node_create)}),
    do: "created"

  defp tree_event_action(%DocTreeEvent{event_type: CMS.Const.doc_tree_action(:node_delete)}),
    do: "deleted"

  defp tree_event_action(%DocTreeEvent{event_type: CMS.Const.doc_tree_action(:node_move)}),
    do: "moved"

  defp tree_event_action(%DocTreeEvent{event_type: type})
       when type in [
              CMS.Const.doc_tree_action(:group_rename),
              CMS.Const.doc_tree_action(:node_rename)
            ],
       do: "renamed"

  defp tree_event_action(%DocTreeEvent{}), do: "modified"

  defp tree_event_label(%DocTreeEvent{
         event_type: CMS.Const.doc_tree_action(:node_create),
         payload: %{"node" => node}
       }),
       do: "Added #{node["title"] || node["id"]}"

  defp tree_event_label(%DocTreeEvent{
         event_type: CMS.Const.doc_tree_action(:node_delete),
         payload: %{"node" => node}
       }),
       do: "Deleted #{node["title"] || node["id"]}"

  defp tree_event_label(%DocTreeEvent{
         event_type: CMS.Const.doc_tree_action(:node_move),
         payload: payload
       }),
       do: "Moved #{payload["title"] || payload["nodeId"]}"

  defp tree_event_label(%DocTreeEvent{event_type: type, payload: payload})
       when type in [
              CMS.Const.doc_tree_action(:group_rename),
              CMS.Const.doc_tree_action(:node_rename)
            ] do
    "Renamed #{payload["before"] || payload["title"]} -> #{payload["after"]}"
  end

  defp tree_event_label(%DocTreeEvent{payload: payload}),
    do: "Updated #{payload["title"] || payload["nodeId"]}"

  defp find_publish_page(%Community{} = community, doc_id, page_node_id) do
    page =
      find_page_by_node_id(community, page_node_id, :public) ||
        find_page_by_node_id(community, page_node_id, :draft) ||
        find_page_by_doc_id(community, doc_id, :public) ||
        find_page_by_doc_id(community, doc_id, :draft)

    case page do
      %DocTreeNode{} = node -> {:ok, node}
      nil -> {:error, {:custom, "docs page has not been added to the side tree"}}
    end
  end

  defp find_page_by_node_id(_community, nil, _stage), do: nil

  defp find_page_by_node_id(%Community{} = community, node_id, stage) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == ^stage)
    |> where([n], n.type == :page)
    |> where([n], n.node_id == ^to_string(node_id))
    |> Repo.one()
  end

  defp find_page_by_doc_id(%Community{} = community, doc_id, stage) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == ^stage)
    |> where([n], n.type == :page)
    |> where([n], n.doc_id == ^doc_id)
    |> Repo.one()
  end

  defp find_publish_group(%Community{} = community, group_id, stage) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == ^stage)
    |> where([n], n.type == :group)
    |> where([n], n.node_id == ^to_string(group_id))
    |> Repo.one()
    |> case do
      %DocTreeNode{} = node -> {:ok, node}
      nil -> {:error, {:custom, "docs page group does not exist"}}
    end
  end

  defp publish_pages_for_drafts(_community, []), do: []

  defp publish_pages_for_drafts(%Community{} = community, doc_ids) do
    public_pages = pages_by_doc_ids(community, doc_ids, :public)
    draft_pages = pages_by_doc_ids(community, doc_ids, :draft)

    public_pages
    |> Enum.concat(draft_pages)
    |> Enum.reduce(%{}, fn page, acc -> Map.put_new(acc, page.doc_id, page) end)
    |> Map.values()
    |> Enum.sort_by(&{&1.index || 0, &1.id})
  end

  defp pages_by_doc_ids(%Community{} = community, doc_ids, stage) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == ^stage)
    |> where([n], n.type == :page)
    |> where([n], n.doc_id in ^doc_ids)
    |> order_by([n], asc: n.index, asc: n.id)
    |> Repo.all()
  end

  defp upsert_public_node(
         %Community{} = community,
         %DocTreeNode{} = draft_node,
         group_id \\ nil,
         doc_id \\ nil,
         public_nodes \\ nil
       ) do
    public_nodes =
      public_nodes ||
        DocTreeNode
        |> where([n], n.community_id == ^community.id)
        |> where([n], n.stage == CMS.Const.stage(:public))
        |> where([n], n.node_id == ^draft_node.node_id)
        |> Repo.all()
        |> Map.new(&{&1.node_id, &1})

    attrs = public_attrs(draft_node, group_id, doc_id)

    case Map.get(public_nodes, draft_node.node_id) ||
           public_node_by_unique_attrs(community, attrs) do
      %DocTreeNode{} = public_node -> ORM.update(public_node, attrs)
      nil -> ORM.create(DocTreeNode, attrs)
    end
  end

  defp public_attrs(%DocTreeNode{} = draft_node, group_id, doc_id) do
    draft_node
    |> Map.take([
      :community_id,
      :node_id,
      :type,
      :title,
      :slug,
      :index,
      :href,
      :marker,
      :badge,
      :hidden,
      :ui_config
    ])
    |> Map.merge(%{stage: CMS.Const.stage(:public), group_id: group_id, doc_id: doc_id})
  end

  defp public_node_by_identity(%Community{} = community, node_id, attrs) do
    public_node_by_node_id(community, node_id) || public_node_by_unique_attrs(community, attrs)
  end

  defp public_node_by_unique_attrs(
         %Community{} = community,
         %{type: :group, group_id: nil} = attrs
       ) do
    public_root_group_by_slug(community, Map.get(attrs, :slug)) ||
      public_root_group_by_title(community, Map.get(attrs, :title))
  end

  defp public_node_by_unique_attrs(%Community{} = community, %{group_id: group_id} = attrs)
       when not is_nil(group_id) do
    public_child_by_slug(community, group_id, Map.get(attrs, :slug)) ||
      public_child_by_title(community, group_id, Map.get(attrs, :title))
  end

  defp public_node_by_unique_attrs(_community, _attrs), do: nil

  defp public_root_group_by_slug(_community, slug) when is_nil(slug) or slug == "", do: nil

  defp public_root_group_by_slug(%Community{} = community, slug) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == CMS.Const.stage(:public))
    |> where([n], n.type == :group)
    |> where([n], is_nil(n.group_id))
    |> where([n], n.slug == ^slug)
    |> order_by([n], desc: n.updated_at, desc: n.id)
    |> limit(1)
    |> Repo.one()
  end

  defp public_root_group_by_title(_community, title) when is_nil(title) or title == "", do: nil

  defp public_root_group_by_title(%Community{} = community, title) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == CMS.Const.stage(:public))
    |> where([n], n.type == :group)
    |> where([n], is_nil(n.group_id))
    |> where([n], n.title == ^title)
    |> order_by([n], desc: n.updated_at, desc: n.id)
    |> limit(1)
    |> Repo.one()
  end

  defp public_child_by_slug(_community, _group_id, slug) when is_nil(slug) or slug == "", do: nil

  defp public_child_by_slug(%Community{} = community, group_id, slug) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == CMS.Const.stage(:public))
    |> where([n], n.group_id == ^group_id)
    |> where([n], n.slug == ^slug)
    |> order_by([n], desc: n.updated_at, desc: n.id)
    |> limit(1)
    |> Repo.one()
  end

  defp public_child_by_title(_community, _group_id, title) when is_nil(title) or title == "",
    do: nil

  defp public_child_by_title(%Community{} = community, group_id, title) do
    DocTreeNode
    |> where([n], n.community_id == ^community.id)
    |> where([n], n.stage == CMS.Const.stage(:public))
    |> where([n], n.group_id == ^group_id)
    |> where([n], n.title == ^title)
    |> order_by([n], desc: n.updated_at, desc: n.id)
    |> limit(1)
    |> Repo.one()
  end

  defp maybe_sync_cover(_community, _published_group, _published_page, false), do: {:ok, :skipped}

  defp maybe_sync_cover(
         %Community{} = community,
         %DocTreeNode{} = group,
         %DocTreeNode{} = page,
         true
       ),
       do: CMS.DocCover.Sync.sync_published_page(community, group, page)
end
