defmodule GroupherServer.CMS.DocTree.TemplateBodyBags do
  @moduledoc """
  Static demo-document BodyBags generated by the Node artiment publisher.

  Keeping the complete publisher output here lets backend-owned demo templates
  participate in the BodyBag-only Article lifecycle without reimplementing a
  Plate serializer in Elixir.

  See `docs/bulk-import/article-publish-import-refactor.md` for the BodyBag-only lifecycle.
  """

  alias GroupherServer.CMS.Artiment.BodyBag

  @schema_version BodyBag.schema_version()

  @default_body_bag %{
    json: ~S([{"children":[{"text":"Start writing your docs draft here."}],"type":"p"}]),
    markdown: "Start writing your docs draft here.\n",
    html:
      ~S(<div class="slate-editor"><div class="slate-p m-0 px-0 py-1"><span><span><span>Start writing your docs draft here.</span></span></span></div></div>),
    toc: [],
    plain_text: "Start writing your docs draft here.",
    digest: "Start writing your docs draft here.",
    body_hash: "2e68d2cfb56f1fdac77fa352e12502434ffc47b52cb99f120d8c603b24b5ffaa",
    schema_version: @schema_version
  }

  @body_bags %{
    "Welcome" => %{
      json:
        ~S([{"children":[{"text":"Welcome"}],"type":"h1"},{"children":[{"text":"Use this draft page as a starting point, then publish when your docs are ready."}],"type":"p"}]),
      markdown:
        "# Welcome\n\nUse this draft page as a starting point, then publish when your docs are ready.\n",
      html:
        ~S(<div class="slate-editor"><h1 data-block-id="welcome" class="slate-h1 relative mb-1 mt-[1.6em] pb-1 font-heading text-4xl font-bold" id="welcome"><span><span><span>Welcome</span></span></span></h1><div class="slate-p m-0 px-0 py-1"><span><span><span>Use this draft page as a starting point, then publish when your docs are ready.</span></span></span></div></div>),
      toc: [%{"id" => "welcome", "level" => 1, "title" => "Welcome"}],
      plain_text:
        "Welcome\nUse this draft page as a starting point, then publish when your docs are ready.",
      digest:
        "Welcome\nUse this draft page as a starting point, then publish when your docs are ready.",
      body_hash: "8b96a13e36d9868dc91cebd3b9befd3916e2ad2aeec2dddd66d3256a000eef64",
      schema_version: @schema_version
    },
    "Quick start" => %{
      json:
        ~S([{"children":[{"text":"Quick start"}],"type":"h1"},{"children":[{"text":"Use this draft page as a starting point, then publish when your docs are ready."}],"type":"p"}]),
      markdown:
        "# Quick start\n\nUse this draft page as a starting point, then publish when your docs are ready.\n",
      html:
        ~S(<div class="slate-editor"><h1 data-block-id="quick-start" class="slate-h1 relative mb-1 mt-[1.6em] pb-1 font-heading text-4xl font-bold" id="quick-start"><span><span><span>Quick start</span></span></span></h1><div class="slate-p"><span><span><span>Use this draft page as a starting point, then publish when your docs are ready.</span></span></span></div></div>),
      toc: [%{"id" => "quick-start", "level" => 1, "title" => "Quick start"}],
      plain_text:
        "Quick start\nUse this draft page as a starting point, then publish when your docs are ready.",
      digest:
        "Quick start\nUse this draft page as a starting point, then publish when your docs are ready.",
      body_hash: "63948b7ff677dedaeeb41c85b8a758574be05ea61eefe0526dad45308b1b60b0",
      schema_version: @schema_version
    },
    "Forum" => %{
      json:
        ~S([{"children":[{"text":"Forum"}],"type":"h1"},{"children":[{"text":"Use this draft page as a starting point, then publish when your docs are ready."}],"type":"p"}]),
      markdown:
        "# Forum\n\nUse this draft page as a starting point, then publish when your docs are ready.\n",
      html:
        ~S(<div class="slate-editor"><h1 data-block-id="forum" class="slate-h1 relative mb-1 mt-[1.6em] pb-1 font-heading text-4xl font-bold" id="forum"><span><span><span>Forum</span></span></span></h1><div class="slate-p"><span><span><span>Use this draft page as a starting point, then publish when your docs are ready.</span></span></span></div></div>),
      toc: [%{"id" => "forum", "level" => 1, "title" => "Forum"}],
      plain_text:
        "Forum\nUse this draft page as a starting point, then publish when your docs are ready.",
      digest:
        "Forum\nUse this draft page as a starting point, then publish when your docs are ready.",
      body_hash: "8dae0992739cdb48250d4f765f5327c4dabd49d1de0d555a0b8389f289eb12e0",
      schema_version: @schema_version
    },
    "Changelog" => %{
      json:
        ~S([{"children":[{"text":"Changelog"}],"type":"h1"},{"children":[{"text":"Use this draft page as a starting point, then publish when your docs are ready."}],"type":"p"}]),
      markdown:
        "# Changelog\n\nUse this draft page as a starting point, then publish when your docs are ready.\n",
      html:
        ~S(<div class="slate-editor"><h1 data-block-id="changelog" class="slate-h1 relative mb-1 mt-[1.6em] pb-1 font-heading text-4xl font-bold" id="changelog"><span><span><span>Changelog</span></span></span></h1><div class="slate-p"><span><span><span>Use this draft page as a starting point, then publish when your docs are ready.</span></span></span></div></div>),
      toc: [%{"id" => "changelog", "level" => 1, "title" => "Changelog"}],
      plain_text:
        "Changelog\nUse this draft page as a starting point, then publish when your docs are ready.",
      digest:
        "Changelog\nUse this draft page as a starting point, then publish when your docs are ready.",
      body_hash: "6ce6fd17c2120c671c45191c580b426397d6223ccb04113528c8446b1e838717",
      schema_version: @schema_version
    }
  }

  @doc "Returns the pre-published BodyBag for one named Docs demo template."
  @spec fetch!(String.t()) :: map()
  def fetch!(title), do: Map.fetch!(@body_bags, title)

  @doc "Returns the pre-published BodyBag used for a blank Docs draft."
  @spec default() :: map()
  def default, do: @default_body_bag
end
