const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guide/index'},
      items: [{type: 'doc', id: 'guide/start'}],
    },
    {type: 'link', label: 'Project', href: 'https://example.com'},
  ],
  api: [{type: 'autogenerated', dirName: 'api'}],
}

export default sidebars
