export const METRIC = {
  /** can not move those values to CSS vars, cause the SSR will break when get it */
  pageBgColor: {
    light: [
      'pure-white',
      'solarized',
      'hacker news',
      'light grey',
      'floral-white',
      'mint-white',
      'pink',
      'todo2',
      'blue2',
      'purple',
      'todo',
    ],
    dark: [
      'charcoal-gray',
      'dark-slate-gray',
      'outer-space',
      'rich-black',
      'coffee-bean',
      'ubuntu',
      'obsidian',
      'solarized',
      'black-chocolate',
      'gunmetal',
      'smoky-black',
      'oxford-blue',
      'eerie-black',
      'daylight-green',
      'jet-black',
      'arsenic',
    ],
  },
}
