defmodule GroupherServer.CMS.DocImport.AdaptersTest do
  use ExUnit.Case, async: true

  alias GroupherServer.CMS.DocImport

  alias GroupherServer.CMS.DocImport.Adapters.{
    Docusaurus,
    Fumadocs,
    Mkdocs,
    Nextra,
    Rspress,
    Starlight,
    Vitepress
  }

  @fixtures Path.expand("../../../fixtures/doc_import", __DIR__)

  test "VitePress adapter preserves its sidebar as a source tree" do
    assert_golden(Vitepress, "vitepress/basic")
  end

  test "VitePress adapter resolves additional config, base paths and static sidebar functions" do
    root = Path.join(@fixtures, "vitepress/additional_config")

    assert {:ok, %{tree: tree, diagnostics: []}} = Vitepress.parse(root)

    assert tree["source"] == %{
             "framework" => "vitepress",
             "root" => "docs/en",
             "configPaths" => ["docs/config.ts"]
           }

    [guide, reference] = tree["navigation"]
    assert guide["routePrefix"] == "/guide/"

    assert Enum.map(hd(guide["children"])["children"], & &1["route"]) == [
             "/guide/what-is-vitepress",
             "/guide/getting-started"
           ]

    [reference_section] = reference["children"]
    [site_config, default_theme] = reference_section["children"]
    assert site_config["sourcePath"] == "docs/en/reference/site-config.md"

    assert Enum.map(default_theme["children"], & &1["sourcePath"]) == [
             "docs/en/reference/default-theme-config.md",
             "docs/en/reference/default-theme-sidebar.md"
           ]
  end

  test "Rspress adapter preserves its sidebar as a source tree" do
    assert_golden(Rspress, "rspress/basic")
  end

  test "Rspress adapter reads _nav, _meta, section headers and i18n labels" do
    root = Path.join(@fixtures, "rspress/auto_navigation")

    assert {:ok, %{tree: tree, diagnostics: []}} = Rspress.parse(root)
    assert tree["source"]["root"] == "docs/en"
    assert tree["source"]["configPaths"] == ["rspress.config.ts", "docs/en/_nav.json"]

    assert Enum.map(tree["navigation"], & &1["title"]) == ["Guide", "API"]
    [guide, api] = tree["navigation"]
    assert Enum.map(guide["children"], & &1["title"]) == ["Getting Started", "More"]

    assert guide["children"] |> hd() |> Map.fetch!("children") |> Enum.map(& &1["title"]) == [
             "Introduction",
             "Quick Start"
           ]

    assert Enum.map(api["children"], & &1["title"]) == ["Overview", "Config"]
  end

  test "Nextra adapter preserves page and directory nesting without invented groups" do
    assert_golden(Nextra, "nextra/basic")
  end

  test "Nextra adapter reads App Router global meta, local constants and JSX labels" do
    root = Path.join(@fixtures, "nextra/app_router")

    assert {:ok, %{tree: tree, diagnostics: []}} = Nextra.parse(root)
    assert tree["source"]["root"] == "app"
    assert tree["source"]["configPaths"] == ["app/_meta.global.tsx"]

    assert Enum.map(tree["navigation"], & &1["title"]) == ["Documentation", "API"]
    [docs, api] = tree["navigation"]
    assert api["children"] |> hd() |> Map.fetch!("route") == "/api"

    assert Enum.map(docs["children"], &{&1["kind"], &1["title"]}) == [
             {"page", "Docs"},
             {"page", "Getting Started"},
             {"section", "More"}
           ]

    [external] = docs["children"] |> List.last() |> Map.fetch!("children")
    assert external["title"] == "External Guide"
    assert external["href"] == "https://example.com/guide"
  end

  test "Docusaurus adapter reads explicit and autogenerated sidebars" do
    root = Path.join(@fixtures, "docusaurus/basic")

    assert {:ok, %{tree: tree, diagnostics: []}} = Docusaurus.parse(root)

    assert tree["source"] == %{
             "framework" => "docusaurus",
             "root" => "docs",
             "configPaths" => ["docusaurus.config.ts", "sidebars.ts"]
           }

    [tutorial, api] = tree["navigation"]
    assert tutorial["title"] == "Tutorial Sidebar"

    assert Enum.map(tutorial["children"], &{&1["kind"], &1["title"]}) == [
             {"page", "Introduction"},
             {"section", "Guides"},
             {"link", "Project"}
           ]

    assert hd(tutorial["children"])["route"] == "/welcome"

    [guide_index, guide] = tutorial["children"] |> Enum.at(1) |> Map.fetch!("children")
    assert guide_index["sourcePath"] == "docs/guide/index.md"
    assert guide["sourcePath"] == "docs/guide/start.md"

    assert api["children"] |> Enum.map(& &1["title"]) == ["Overview", "Client"]
  end

  test "MkDocs adapter reads nested nav, bare pages and external links" do
    root = Path.join(@fixtures, "mkdocs/basic")

    assert {:ok, %{tree: tree, diagnostics: []}} = Mkdocs.parse(root)

    assert tree["source"] == %{
             "framework" => "mkdocs",
             "root" => "content",
             "configPaths" => ["mkdocs.yml"]
           }

    [scope] = tree["navigation"]

    assert Enum.map(scope["children"], &{&1["kind"], &1["title"]}) == [
             {"page", "Home"},
             {"section", "Guide"},
             {"page", "API"},
             {"link", "Project"}
           ]

    [start, advanced] = scope["children"] |> Enum.at(1) |> Map.fetch!("children")
    assert start["sourcePath"] == "content/guide/start.md"
    assert advanced["title"] == "Advanced Topics"
  end

  test "MkDocs adapter infers navigation when nav is absent" do
    root = Path.join(@fixtures, "mkdocs/automatic")

    assert {:ok, %{tree: tree, diagnostics: []}} = Mkdocs.parse(root)
    [scope] = tree["navigation"]

    assert Enum.map(scope["children"], &{&1["kind"], &1["title"]}) == [
             {"page", "Welcome"},
             {"section", "Reference"}
           ]
  end

  test "Starlight adapter reads explicit, nested and autogenerated sidebar entries" do
    root = Path.join(@fixtures, "starlight/basic")

    assert {:ok, %{tree: tree, diagnostics: []}} = Starlight.parse(root)

    assert tree["source"] == %{
             "framework" => "starlight",
             "root" => "src/content/docs",
             "configPaths" => ["astro.config.mjs"]
           }

    [scope] = tree["navigation"]

    assert Enum.map(scope["children"], &{&1["kind"], &1["title"]}) == [
             {"page", "Home"},
             {"section", "Guides"},
             {"section", "API"},
             {"link", "Project"}
           ]

    [start, advanced] = scope["children"] |> Enum.at(1) |> Map.fetch!("children")
    assert start["title"] == "Getting Started"
    assert advanced["sourcePath"] == "src/content/docs/guides/advanced.mdx"
  end

  test "Starlight reports a missing sidebar page without crashing" do
    root = Path.join(System.tmp_dir!(), "starlight-missing-#{System.unique_integer([:positive])}")
    on_exit(fn -> File.rm_rf(root) end)
    File.mkdir_p!(Path.join(root, "src/content/docs"))

    File.write!(
      Path.join(root, "astro.config.mjs"),
      "import starlight from '@astrojs/starlight'; starlight({sidebar: [{label: 'Missing', slug: 'missing'}]})"
    )

    assert {:ok, %{tree: tree, diagnostics: [diagnostic]}} = Starlight.parse(root)
    assert diagnostic.code == "page_not_found"
    assert diagnostic.source_id == "missing"
    assert tree["navigation"] |> hd() |> Map.fetch!("children") == []
  end

  test "Docusaurus reports a missing sidebar page without inventing sourcePath" do
    root =
      Path.join(System.tmp_dir!(), "docusaurus-missing-#{System.unique_integer([:positive])}")

    on_exit(fn -> File.rm_rf(root) end)
    File.mkdir_p!(Path.join(root, "docs"))
    File.write!(Path.join(root, "docusaurus.config.ts"), "export default {}")
    File.write!(Path.join(root, "sidebars.ts"), "export default {docs: ['missing']}")

    assert {:ok, %{tree: tree, diagnostics: [diagnostic]}} = Docusaurus.parse(root)
    assert diagnostic.code == "page_not_found"
    assert diagnostic.source_id == "missing"
    assert tree["navigation"] |> hd() |> Map.fetch!("children") == []
  end

  test "Fumadocs adapter reads meta order, separators, folders, wildcards and links" do
    root = Path.join(@fixtures, "fumadocs/basic")

    assert {:ok, %{tree: tree, diagnostics: []}} = Fumadocs.parse(root)

    assert tree["source"] == %{
             "framework" => "fumadocs",
             "root" => "content/docs",
             "configPaths" => [
               "source.config.ts",
               "content/docs/guide/meta.json",
               "content/docs/meta.json"
             ]
           }

    [scope] = tree["navigation"]
    assert scope["title"] == "Fixture Docs"

    assert Enum.map(scope["children"], &{&1["kind"], &1["title"]}) == [
             {"page", "Welcome"},
             {"section", "Guides"}
           ]

    guide_children = scope["children"] |> Enum.at(1) |> Map.fetch!("children")

    assert Enum.map(guide_children, &{&1["kind"], &1["title"]}) == [
             {"section", "Guide"},
             {"link", "Project"},
             {"page", "Changelog"}
           ]
  end

  test "Fumadocs reports explicitly configured missing pages and folders" do
    root = Path.join(System.tmp_dir!(), "fumadocs-missing-#{System.unique_integer([:positive])}")
    docs = Path.join(root, "content/docs")
    on_exit(fn -> File.rm_rf(root) end)
    File.mkdir_p!(docs)
    File.write!(Path.join(root, "source.config.ts"), "export const docs = {}")

    File.write!(
      Path.join(docs, "meta.json"),
      Jason.encode!(%{
        "pages" => [
          "missing-page",
          %{"type" => "folder", "name" => "missing-folder"}
        ]
      })
    )

    assert {:ok, %{tree: tree, diagnostics: diagnostics}} = Fumadocs.parse(root)

    assert Enum.map(diagnostics, &{&1.code, &1.source_id}) == [
             {"page_not_found", "missing-page"},
             {"folder_not_found", "missing-folder"}
           ]

    assert tree["navigation"] |> hd() |> Map.fetch!("children") == []
  end

  test "framework detection delegates to the matching adapter" do
    for {fixture, framework} <- [
          {"vitepress/basic", "vitepress"},
          {"rspress/basic", "rspress"},
          {"nextra/basic", "nextra"},
          {"docusaurus/basic", "docusaurus"},
          {"mkdocs/basic", "mkdocs"},
          {"starlight/basic", "starlight"},
          {"fumadocs/basic", "fumadocs"}
        ] do
      assert {:ok, %{tree: %{"source" => %{"framework" => ^framework}}}} =
               DocImport.parse_tree(Path.join(@fixtures, fixture))
    end
  end

  test "static adapters reject dynamic configuration without executing it" do
    root =
      Path.join(System.tmp_dir!(), "doc-import-dynamic-#{System.unique_integer([:positive])}")

    config = Path.join(root, "docs/.vitepress/config.ts")
    on_exit(fn -> File.rm_rf(root) end)

    File.mkdir_p!(Path.dirname(config))

    File.write!(
      config,
      "export default defineConfig({ themeConfig: { sidebar: makeSidebar() } })"
    )

    assert {:error, %{code: "dynamic_config"}} = Vitepress.parse(root)
  end

  defp assert_golden(adapter, fixture) do
    root = Path.join(@fixtures, fixture)
    expected = root |> Path.join("expected/tree.json") |> File.read!() |> Jason.decode!()

    assert {:ok, %{tree: tree, diagnostics: []}} = adapter.parse(root)
    assert tree == expected
  end
end
