export const INTEGRATE_ANALYSIS_TOOLS = [
  {
    key: 'ga',
    title: 'dsb.third_part.ga.title',
    desc: 'dsb.third_part.ga.desc',
    detail: 'dsb.third_part.ga.detail',
    trackLabel: 'dsb.third_part.ga.track_label',
    trackDesc: 'dsb.third_part.ga.track_desc',
    placeholder: 'dsb.third_part.ga.placeholder',
    homepage: 'https://developers.google.com/analytics',
  },

  {
    key: 'gtm',
    title: 'dsb.third_part.gtm.title',
    desc: 'dsb.third_part.gtm.desc',
    detail: 'dsb.third_part.gtm.detail',
    trackLabel: 'dsb.third_part.gtm.track_label',
    trackDesc: 'dsb.third_part.gtm.track_desc',
    placeholder: 'dsb.third_part.gtm.placeholder',
    homepage: 'https://developers.google.com/tag-platform/tag-manager',
  },

  {
    key: 'fb_pixel',
    title: 'dsb.third_part.fb_pixel.title',
    desc: 'dsb.third_part.fb_pixel.desc',
    detail: 'dsb.third_part.fb_pixel.detail',
    trackLabel: 'dsb.third_part.fb_pixel.track_label',
    trackDesc: 'dsb.third_part.fb_pixel.track_desc',
    placeholder: 'dsb.third_part.fb_pixel.placeholder',
    homepage: 'https://developers.facebook.com/docs/meta-pixel',
  },

  {
    key: 'hotjar',
    title: 'dsb.third_part.hotjar.title',
    desc: 'dsb.third_part.hotjar.desc',
    detail: 'dsb.third_part.hotjar.detail',
    trackLabel: 'dsb.third_part.hotjar.track_label',
    trackDesc: 'dsb.third_part.hotjar.track_desc',
    placeholder: 'dsb.third_part.hotjar.placeholder',
    homepage: 'https://www.hotjar.com/guides/',
  },

  {
    key: 'clarity',
    title: 'dsb.third_part.clarity.title',
    desc: 'dsb.third_part.clarity.desc',
    detail: 'dsb.third_part.clarity.detail',
    trackLabel: 'dsb.third_part.clarity.track_label',
    trackDesc: 'dsb.third_part.clarity.track_desc',
    placeholder: 'dsb.third_part.clarity.placeholder',
    homepage: 'https://learn.microsoft.com/zh-cn/clarity/',
  },

  {
    key: 'plausible',
    title: 'dsb.third_part.plausible.title',
    desc: 'dsb.third_part.plausible.desc',
    detail: 'dsb.third_part.plausible.detail',
    trackLabel: 'dsb.third_part.plausible.track_label',
    trackDesc: 'dsb.third_part.plausible.track_desc',
    placeholder: 'dsb.third_part.plausible.placeholder',
    homepage: 'https://plausible.io/docs',
  },

  {
    key: 'fathom',
    title: 'dsb.third_part.fathom.title',
    desc: 'dsb.third_part.fathom.desc',
    detail: 'dsb.third_part.fathom.detail',
    trackLabel: 'dsb.third_part.fathom.track_label',
    trackDesc: 'dsb.third_part.fathom.track_desc',
    placeholder: 'dsb.third_part.fathom.placeholder',
    homepage: 'https://usefathom.com/docs',
  },

  {
    key: 'umami',
    title: 'dsb.third_part.umami.title',
    desc: 'dsb.third_part.umami.desc',
    detail: 'dsb.third_part.umami.detail',
    trackLabel: 'dsb.third_part.umami.track_label',
    trackDesc: 'dsb.third_part.umami.track_desc',
    placeholder: 'dsb.third_part.umami.placeholder',
    homepage: 'https://umami.is/docs',
  },

  {
    key: 'matomo',
    title: 'dsb.third_part.matomo.title',
    desc: 'dsb.third_part.matomo.desc',
    detail: 'dsb.third_part.matomo.detail',
    trackLabel: 'dsb.third_part.matomo.track_label',
    trackDesc: 'dsb.third_part.matomo.track_desc',
    placeholder: 'dsb.third_part.matomo.placeholder',
    homepage: 'https://developer.matomo.org/integration',
  },
] as const
