// Generated by scripts/generate-visitor-location-data.mjs. Do not edit manually.
// Source: country-state-city 3.2.1 (MIT). Country and allowlisted region label points only.

export const VISITOR_LOCATION_DATA_VERSION = 'country-state-city@3.2.1'

export const COUNTRY_LOCATION_POINTS = {
  AF: {
    name: 'Afghanistan',
    location: [33, 65],
  },
  AX: {
    name: 'Aland Islands',
    location: [60.116667, 19.9],
  },
  AL: {
    name: 'Albania',
    location: [41, 20],
  },
  DZ: {
    name: 'Algeria',
    location: [28, 3],
  },
  AS: {
    name: 'American Samoa',
    location: [-14.33333333, -170],
  },
  AD: {
    name: 'Andorra',
    location: [42.5, 1.5],
  },
  AO: {
    name: 'Angola',
    location: [-12.5, 18.5],
  },
  AI: {
    name: 'Anguilla',
    location: [18.25, -63.16666666],
  },
  AQ: {
    name: 'Antarctica',
    location: [-74.65, 4.48],
  },
  AG: {
    name: 'Antigua And Barbuda',
    location: [17.05, -61.8],
  },
  AR: {
    name: 'Argentina',
    location: [-34, -64],
  },
  AM: {
    name: 'Armenia',
    location: [40, 45],
  },
  AW: {
    name: 'Aruba',
    location: [12.5, -69.96666666],
  },
  AU: {
    name: 'Australia',
    location: [-27, 133],
  },
  AT: {
    name: 'Austria',
    location: [47.33333333, 13.33333333],
  },
  AZ: {
    name: 'Azerbaijan',
    location: [40.5, 47.5],
  },
  BS: {
    name: 'The Bahamas',
    location: [24.25, -76],
  },
  BH: {
    name: 'Bahrain',
    location: [26, 50.55],
  },
  BD: {
    name: 'Bangladesh',
    location: [24, 90],
  },
  BB: {
    name: 'Barbados',
    location: [13.16666666, -59.53333333],
  },
  BY: {
    name: 'Belarus',
    location: [53, 28],
  },
  BE: {
    name: 'Belgium',
    location: [50.83333333, 4],
  },
  BZ: {
    name: 'Belize',
    location: [17.25, -88.75],
  },
  BJ: {
    name: 'Benin',
    location: [9.5, 2.25],
  },
  BM: {
    name: 'Bermuda',
    location: [32.33333333, -64.75],
  },
  BT: {
    name: 'Bhutan',
    location: [27.5, 90.5],
  },
  BO: {
    name: 'Bolivia',
    location: [-17, -65],
  },
  BA: {
    name: 'Bosnia and Herzegovina',
    location: [44, 18],
  },
  BW: {
    name: 'Botswana',
    location: [-22, 24],
  },
  BV: {
    name: 'Bouvet Island',
    location: [-54.43333333, 3.4],
  },
  BR: {
    name: 'Brazil',
    location: [-10, -55],
  },
  IO: {
    name: 'British Indian Ocean Territory',
    location: [-6, 71.5],
  },
  BN: {
    name: 'Brunei',
    location: [4.5, 114.66666666],
  },
  BG: {
    name: 'Bulgaria',
    location: [43, 25],
  },
  BF: {
    name: 'Burkina Faso',
    location: [13, -2],
  },
  BI: {
    name: 'Burundi',
    location: [-3.5, 30],
  },
  KH: {
    name: 'Cambodia',
    location: [13, 105],
  },
  CM: {
    name: 'Cameroon',
    location: [6, 12],
  },
  CA: {
    name: 'Canada',
    location: [60, -95],
  },
  CV: {
    name: 'Cape Verde',
    location: [16, -24],
  },
  KY: {
    name: 'Cayman Islands',
    location: [19.5, -80.5],
  },
  CF: {
    name: 'Central African Republic',
    location: [7, 21],
  },
  TD: {
    name: 'Chad',
    location: [15, 19],
  },
  CL: {
    name: 'Chile',
    location: [-30, -71],
  },
  CN: {
    name: 'China',
    location: [35, 105],
  },
  CX: {
    name: 'Christmas Island',
    location: [-10.5, 105.66666666],
  },
  CC: {
    name: 'Cocos (Keeling) Islands',
    location: [-12.5, 96.83333333],
  },
  CO: {
    name: 'Colombia',
    location: [4, -72],
  },
  KM: {
    name: 'Comoros',
    location: [-12.16666666, 44.25],
  },
  CG: {
    name: 'Congo',
    location: [-1, 15],
  },
  CD: {
    name: 'Democratic Republic of the Congo',
    location: [0, 25],
  },
  CK: {
    name: 'Cook Islands',
    location: [-21.23333333, -159.76666666],
  },
  CR: {
    name: 'Costa Rica',
    location: [10, -84],
  },
  CI: {
    name: "Cote D'Ivoire (Ivory Coast)",
    location: [8, -5],
  },
  HR: {
    name: 'Croatia',
    location: [45.16666666, 15.5],
  },
  CU: {
    name: 'Cuba',
    location: [21.5, -80],
  },
  CY: {
    name: 'Cyprus',
    location: [35, 33],
  },
  CZ: {
    name: 'Czech Republic',
    location: [49.75, 15.5],
  },
  DK: {
    name: 'Denmark',
    location: [56, 10],
  },
  DJ: {
    name: 'Djibouti',
    location: [11.5, 43],
  },
  DM: {
    name: 'Dominica',
    location: [15.41666666, -61.33333333],
  },
  DO: {
    name: 'Dominican Republic',
    location: [19, -70.66666666],
  },
  TL: {
    name: 'East Timor',
    location: [-8.83333333, 125.91666666],
  },
  EC: {
    name: 'Ecuador',
    location: [-2, -77.5],
  },
  EG: {
    name: 'Egypt',
    location: [27, 30],
  },
  SV: {
    name: 'El Salvador',
    location: [13.83333333, -88.91666666],
  },
  GQ: {
    name: 'Equatorial Guinea',
    location: [2, 10],
  },
  ER: {
    name: 'Eritrea',
    location: [15, 39],
  },
  EE: {
    name: 'Estonia',
    location: [59, 26],
  },
  ET: {
    name: 'Ethiopia',
    location: [8, 38],
  },
  FK: {
    name: 'Falkland Islands',
    location: [-51.75, -59],
  },
  FO: {
    name: 'Faroe Islands',
    location: [62, -7],
  },
  FJ: {
    name: 'Fiji Islands',
    location: [-18, 175],
  },
  FI: {
    name: 'Finland',
    location: [64, 26],
  },
  FR: {
    name: 'France',
    location: [46, 2],
  },
  GF: {
    name: 'French Guiana',
    location: [4, -53],
  },
  PF: {
    name: 'French Polynesia',
    location: [-15, -140],
  },
  TF: {
    name: 'French Southern Territories',
    location: [-49.25, 69.167],
  },
  GA: {
    name: 'Gabon',
    location: [-1, 11.75],
  },
  GM: {
    name: 'The Gambia',
    location: [13.46666666, -16.56666666],
  },
  GE: {
    name: 'Georgia',
    location: [42, 43.5],
  },
  DE: {
    name: 'Germany',
    location: [51, 9],
  },
  GH: {
    name: 'Ghana',
    location: [8, -2],
  },
  GI: {
    name: 'Gibraltar',
    location: [36.13333333, -5.35],
  },
  GR: {
    name: 'Greece',
    location: [39, 22],
  },
  GL: {
    name: 'Greenland',
    location: [72, -40],
  },
  GD: {
    name: 'Grenada',
    location: [12.11666666, -61.66666666],
  },
  GP: {
    name: 'Guadeloupe',
    location: [16.25, -61.583333],
  },
  GU: {
    name: 'Guam',
    location: [13.46666666, 144.78333333],
  },
  GT: {
    name: 'Guatemala',
    location: [15.5, -90.25],
  },
  GG: {
    name: 'Guernsey and Alderney',
    location: [49.46666666, -2.58333333],
  },
  GN: {
    name: 'Guinea',
    location: [11, -10],
  },
  GW: {
    name: 'Guinea-Bissau',
    location: [12, -15],
  },
  GY: {
    name: 'Guyana',
    location: [5, -59],
  },
  HT: {
    name: 'Haiti',
    location: [19, -72.41666666],
  },
  HM: {
    name: 'Heard Island and McDonald Islands',
    location: [-53.1, 72.51666666],
  },
  HN: {
    name: 'Honduras',
    location: [15, -86.5],
  },
  HK: {
    name: 'Hong Kong S.A.R.',
    location: [22.25, 114.16666666],
  },
  HU: {
    name: 'Hungary',
    location: [47, 20],
  },
  IS: {
    name: 'Iceland',
    location: [65, -18],
  },
  IN: {
    name: 'India',
    location: [20, 77],
  },
  ID: {
    name: 'Indonesia',
    location: [-5, 120],
  },
  IR: {
    name: 'Iran',
    location: [32, 53],
  },
  IQ: {
    name: 'Iraq',
    location: [33, 44],
  },
  IE: {
    name: 'Ireland',
    location: [53, -8],
  },
  IL: {
    name: 'Israel',
    location: [31.5, 34.75],
  },
  IT: {
    name: 'Italy',
    location: [42.83333333, 12.83333333],
  },
  JM: {
    name: 'Jamaica',
    location: [18.25, -77.5],
  },
  JP: {
    name: 'Japan',
    location: [36, 138],
  },
  JE: {
    name: 'Jersey',
    location: [49.25, -2.16666666],
  },
  JO: {
    name: 'Jordan',
    location: [31, 36],
  },
  KZ: {
    name: 'Kazakhstan',
    location: [48, 68],
  },
  KE: {
    name: 'Kenya',
    location: [1, 38],
  },
  KI: {
    name: 'Kiribati',
    location: [1.41666666, 173],
  },
  KP: {
    name: 'North Korea',
    location: [40, 127],
  },
  KR: {
    name: 'South Korea',
    location: [37, 127.5],
  },
  KW: {
    name: 'Kuwait',
    location: [29.5, 45.75],
  },
  KG: {
    name: 'Kyrgyzstan',
    location: [41, 75],
  },
  LA: {
    name: 'Laos',
    location: [18, 105],
  },
  LV: {
    name: 'Latvia',
    location: [57, 25],
  },
  LB: {
    name: 'Lebanon',
    location: [33.83333333, 35.83333333],
  },
  LS: {
    name: 'Lesotho',
    location: [-29.5, 28.5],
  },
  LR: {
    name: 'Liberia',
    location: [6.5, -9.5],
  },
  LY: {
    name: 'Libya',
    location: [25, 17],
  },
  LI: {
    name: 'Liechtenstein',
    location: [47.26666666, 9.53333333],
  },
  LT: {
    name: 'Lithuania',
    location: [56, 24],
  },
  LU: {
    name: 'Luxembourg',
    location: [49.75, 6.16666666],
  },
  MO: {
    name: 'Macau S.A.R.',
    location: [22.16666666, 113.55],
  },
  MK: {
    name: 'Macedonia',
    location: [41.83333333, 22],
  },
  MG: {
    name: 'Madagascar',
    location: [-20, 47],
  },
  MW: {
    name: 'Malawi',
    location: [-13.5, 34],
  },
  MY: {
    name: 'Malaysia',
    location: [2.5, 112.5],
  },
  MV: {
    name: 'Maldives',
    location: [3.25, 73],
  },
  ML: {
    name: 'Mali',
    location: [17, -4],
  },
  MT: {
    name: 'Malta',
    location: [35.83333333, 14.58333333],
  },
  IM: {
    name: 'Man (Isle of)',
    location: [54.25, -4.5],
  },
  MH: {
    name: 'Marshall Islands',
    location: [9, 168],
  },
  MQ: {
    name: 'Martinique',
    location: [14.666667, -61],
  },
  MR: {
    name: 'Mauritania',
    location: [20, -12],
  },
  MU: {
    name: 'Mauritius',
    location: [-20.28333333, 57.55],
  },
  YT: {
    name: 'Mayotte',
    location: [-12.83333333, 45.16666666],
  },
  MX: {
    name: 'Mexico',
    location: [23, -102],
  },
  FM: {
    name: 'Micronesia',
    location: [6.91666666, 158.25],
  },
  MD: {
    name: 'Moldova',
    location: [47, 29],
  },
  MC: {
    name: 'Monaco',
    location: [43.73333333, 7.4],
  },
  MN: {
    name: 'Mongolia',
    location: [46, 105],
  },
  ME: {
    name: 'Montenegro',
    location: [42.5, 19.3],
  },
  MS: {
    name: 'Montserrat',
    location: [16.75, -62.2],
  },
  MA: {
    name: 'Morocco',
    location: [32, -5],
  },
  MZ: {
    name: 'Mozambique',
    location: [-18.25, 35],
  },
  MM: {
    name: 'Myanmar',
    location: [22, 98],
  },
  NA: {
    name: 'Namibia',
    location: [-22, 17],
  },
  NR: {
    name: 'Nauru',
    location: [-0.53333333, 166.91666666],
  },
  NP: {
    name: 'Nepal',
    location: [28, 84],
  },
  BQ: {
    name: 'Bonaire, Sint Eustatius and Saba',
    location: [12.15, -68.266667],
  },
  NL: {
    name: 'Netherlands',
    location: [52.5, 5.75],
  },
  NC: {
    name: 'New Caledonia',
    location: [-21.5, 165.5],
  },
  NZ: {
    name: 'New Zealand',
    location: [-41, 174],
  },
  NI: {
    name: 'Nicaragua',
    location: [13, -85],
  },
  NE: {
    name: 'Niger',
    location: [16, 8],
  },
  NG: {
    name: 'Nigeria',
    location: [10, 8],
  },
  NU: {
    name: 'Niue',
    location: [-19.03333333, -169.86666666],
  },
  NF: {
    name: 'Norfolk Island',
    location: [-29.03333333, 167.95],
  },
  MP: {
    name: 'Northern Mariana Islands',
    location: [15.2, 145.75],
  },
  NO: {
    name: 'Norway',
    location: [62, 10],
  },
  OM: {
    name: 'Oman',
    location: [21, 57],
  },
  PK: {
    name: 'Pakistan',
    location: [30, 70],
  },
  PW: {
    name: 'Palau',
    location: [7.5, 134.5],
  },
  PS: {
    name: 'Palestinian Territory Occupied',
    location: [31.9, 35.2],
  },
  PA: {
    name: 'Panama',
    location: [9, -80],
  },
  PG: {
    name: 'Papua new Guinea',
    location: [-6, 147],
  },
  PY: {
    name: 'Paraguay',
    location: [-23, -58],
  },
  PE: {
    name: 'Peru',
    location: [-10, -76],
  },
  PH: {
    name: 'Philippines',
    location: [13, 122],
  },
  PN: {
    name: 'Pitcairn Island',
    location: [-25.06666666, -130.1],
  },
  PL: {
    name: 'Poland',
    location: [52, 20],
  },
  PT: {
    name: 'Portugal',
    location: [39.5, -8],
  },
  PR: {
    name: 'Puerto Rico',
    location: [18.25, -66.5],
  },
  QA: {
    name: 'Qatar',
    location: [25.5, 51.25],
  },
  RE: {
    name: 'Reunion',
    location: [-21.15, 55.5],
  },
  RO: {
    name: 'Romania',
    location: [46, 25],
  },
  RU: {
    name: 'Russia',
    location: [60, 100],
  },
  RW: {
    name: 'Rwanda',
    location: [-2, 30],
  },
  SH: {
    name: 'Saint Helena',
    location: [-15.95, -5.7],
  },
  KN: {
    name: 'Saint Kitts And Nevis',
    location: [17.33333333, -62.75],
  },
  LC: {
    name: 'Saint Lucia',
    location: [13.88333333, -60.96666666],
  },
  PM: {
    name: 'Saint Pierre and Miquelon',
    location: [46.83333333, -56.33333333],
  },
  VC: {
    name: 'Saint Vincent And The Grenadines',
    location: [13.25, -61.2],
  },
  BL: {
    name: 'Saint-Barthelemy',
    location: [18.5, -63.41666666],
  },
  MF: {
    name: 'Saint-Martin (French part)',
    location: [18.08333333, -63.95],
  },
  WS: {
    name: 'Samoa',
    location: [-13.58333333, -172.33333333],
  },
  SM: {
    name: 'San Marino',
    location: [43.76666666, 12.41666666],
  },
  ST: {
    name: 'Sao Tome and Principe',
    location: [1, 7],
  },
  SA: {
    name: 'Saudi Arabia',
    location: [25, 45],
  },
  SN: {
    name: 'Senegal',
    location: [14, -14],
  },
  RS: {
    name: 'Serbia',
    location: [44, 21],
  },
  SC: {
    name: 'Seychelles',
    location: [-4.58333333, 55.66666666],
  },
  SL: {
    name: 'Sierra Leone',
    location: [8.5, -11.5],
  },
  SG: {
    name: 'Singapore',
    location: [1.36666666, 103.8],
  },
  SK: {
    name: 'Slovakia',
    location: [48.66666666, 19.5],
  },
  SI: {
    name: 'Slovenia',
    location: [46.11666666, 14.81666666],
  },
  SB: {
    name: 'Solomon Islands',
    location: [-8, 159],
  },
  SO: {
    name: 'Somalia',
    location: [10, 49],
  },
  ZA: {
    name: 'South Africa',
    location: [-29, 24],
  },
  GS: {
    name: 'South Georgia',
    location: [-54.5, -37],
  },
  SS: {
    name: 'South Sudan',
    location: [7, 30],
  },
  ES: {
    name: 'Spain',
    location: [40, -4],
  },
  LK: {
    name: 'Sri Lanka',
    location: [7, 81],
  },
  SD: {
    name: 'Sudan',
    location: [15, 30],
  },
  SR: {
    name: 'Suriname',
    location: [4, -56],
  },
  SJ: {
    name: 'Svalbard And Jan Mayen Islands',
    location: [78, 20],
  },
  SZ: {
    name: 'Swaziland',
    location: [-26.5, 31.5],
  },
  SE: {
    name: 'Sweden',
    location: [62, 15],
  },
  CH: {
    name: 'Switzerland',
    location: [47, 8],
  },
  SY: {
    name: 'Syria',
    location: [35, 38],
  },
  TW: {
    name: 'Taiwan',
    location: [23.5, 121],
  },
  TJ: {
    name: 'Tajikistan',
    location: [39, 71],
  },
  TZ: {
    name: 'Tanzania',
    location: [-6, 35],
  },
  TH: {
    name: 'Thailand',
    location: [15, 100],
  },
  TG: {
    name: 'Togo',
    location: [8, 1.16666666],
  },
  TK: {
    name: 'Tokelau',
    location: [-9, -172],
  },
  TO: {
    name: 'Tonga',
    location: [-20, -175],
  },
  TT: {
    name: 'Trinidad And Tobago',
    location: [11, -61],
  },
  TN: {
    name: 'Tunisia',
    location: [34, 9],
  },
  TR: {
    name: 'Turkey',
    location: [39, 35],
  },
  TM: {
    name: 'Turkmenistan',
    location: [40, 60],
  },
  TC: {
    name: 'Turks And Caicos Islands',
    location: [21.75, -71.58333333],
  },
  TV: {
    name: 'Tuvalu',
    location: [-8, 178],
  },
  UG: {
    name: 'Uganda',
    location: [1, 32],
  },
  UA: {
    name: 'Ukraine',
    location: [49, 32],
  },
  AE: {
    name: 'United Arab Emirates',
    location: [24, 54],
  },
  GB: {
    name: 'United Kingdom',
    location: [54, -2],
  },
  US: {
    name: 'United States',
    location: [38, -97],
  },
  UM: {
    name: 'United States Minor Outlying Islands',
    location: [0, 0],
  },
  UY: {
    name: 'Uruguay',
    location: [-33, -56],
  },
  UZ: {
    name: 'Uzbekistan',
    location: [41, 64],
  },
  VU: {
    name: 'Vanuatu',
    location: [-16, 167],
  },
  VA: {
    name: 'Vatican City State (Holy See)',
    location: [41.9, 12.45],
  },
  VE: {
    name: 'Venezuela',
    location: [8, -66],
  },
  VN: {
    name: 'Vietnam',
    location: [16.16666666, 107.83333333],
  },
  VG: {
    name: 'Virgin Islands (British)',
    location: [18.431383, -64.62305],
  },
  VI: {
    name: 'Virgin Islands (US)',
    location: [18.34, -64.93],
  },
  WF: {
    name: 'Wallis And Futuna Islands',
    location: [-13.3, -176.2],
  },
  EH: {
    name: 'Western Sahara',
    location: [24.5, -13],
  },
  YE: {
    name: 'Yemen',
    location: [15, 48],
  },
  ZM: {
    name: 'Zambia',
    location: [-15, 30],
  },
  ZW: {
    name: 'Zimbabwe',
    location: [-20, 30],
  },
  XK: {
    name: 'Kosovo',
    location: [42.5612909, 20.3403035],
  },
  CW: {
    name: 'Curaçao',
    location: [12.116667, -68.933333],
  },
  SX: {
    name: 'Sint Maarten (Dutch part)',
    location: [18.033333, -63.05],
  },
} as const

export const REGION_LOCATION_POINTS = {
  'CN-AH': {
    name: 'Anhui',
    location: [30.6006773, 117.9249002],
  },
  'CN-BJ': {
    name: 'Beijing',
    location: [39.9041999, 116.4073963],
  },
  'CN-CQ': {
    name: 'Chongqing',
    location: [29.4315861, 106.912251],
  },
  'CN-FJ': {
    name: 'Fujian',
    location: [26.4836842, 117.9249002],
  },
  'CN-GS': {
    name: 'Gansu',
    location: [35.7518326, 104.2861116],
  },
  'CN-GD': {
    name: 'Guangdong',
    location: [23.3790333, 113.7632828],
  },
  'CN-GX': {
    name: 'Guangxi Zhuang',
    location: [23.7247599, 108.8076195],
  },
  'CN-GZ': {
    name: 'Guizhou',
    location: [26.8429645, 107.2902839],
  },
  'CN-HI': {
    name: 'Hainan',
    location: [19.5663947, 109.949686],
  },
  'CN-HE': {
    name: 'Hebei',
    location: [37.8956594, 114.9042208],
  },
  'CN-HL': {
    name: 'Heilongjiang',
    location: [47.1216472, 128.738231],
  },
  'CN-HA': {
    name: 'Henan',
    location: [34.2904302, 113.3823545],
  },
  'CN-HK': {
    name: 'Hong Kong SAR',
    location: [22.3193039, 114.1693611],
  },
  'CN-HB': {
    name: 'Hubei',
    location: [30.7378118, 112.2384017],
  },
  'CN-HN': {
    name: 'Hunan',
    location: [36.7341294, -95.9344902],
  },
  'CN-NM': {
    name: 'Inner Mongolia',
    location: [43.37822, 115.0594815],
  },
  'CN-JS': {
    name: 'Jiangsu',
    location: [33.1401715, 119.7889248],
  },
  'CN-JX': {
    name: 'Jiangxi',
    location: [27.0874564, 114.9042208],
  },
  'CN-JL': {
    name: 'Jilin',
    location: [43.837883, 126.549572],
  },
  'CN-LN': {
    name: 'Liaoning',
    location: [41.9436543, 122.5290376],
  },
  'CN-MO': {
    name: 'Macau SAR',
    location: [22.198745, 113.543873],
  },
  'CN-NX': {
    name: 'Ningxia Huizu',
    location: [37.198731, 106.1580937],
  },
  'CN-QH': {
    name: 'Qinghai',
    location: [35.744798, 96.4077358],
  },
  'CN-SN': {
    name: 'Shaanxi',
    location: [35.3939908, 109.1880047],
  },
  'CN-SD': {
    name: 'Shandong',
    location: [37.8006064, -122.2699918],
  },
  'CN-SH': {
    name: 'Shanghai',
    location: [31.230416, 121.473701],
  },
  'CN-SX': {
    name: 'Shanxi',
    location: [37.2425649, 111.8568586],
  },
  'CN-SC': {
    name: 'Sichuan',
    location: [30.2638032, 102.8054753],
  },
  'CN-TW': {
    name: 'Taiwan',
    location: [23.69781, 120.960515],
  },
  'CN-TJ': {
    name: 'Tianjin',
    location: [39.1252291, 117.0153435],
  },
  'CN-XJ': {
    name: 'Xinjiang',
    location: [42.5246357, 87.5395855],
  },
  'CN-XZ': {
    name: 'Xizang',
    location: [30.1533605, 88.7878678],
  },
  'CN-YN': {
    name: 'Yunnan',
    location: [24.4752847, 101.3431058],
  },
  'CN-ZJ': {
    name: 'Zhejiang',
    location: [29.1416432, 119.7889248],
  },
  'US-AL': {
    name: 'Alabama',
    location: [32.3182314, -86.902298],
  },
  'US-AK': {
    name: 'Alaska',
    location: [64.2008413, -149.4936733],
  },
  'US-AS': {
    name: 'American Samoa',
    location: [-14.270972, -170.132217],
  },
  'US-AZ': {
    name: 'Arizona',
    location: [34.0489281, -111.0937311],
  },
  'US-AR': {
    name: 'Arkansas',
    location: [35.20105, -91.8318334],
  },
  'US-UM-81': {
    name: 'Baker Island',
    location: [0.1936266, -176.476908],
  },
  'US-CA': {
    name: 'California',
    location: [36.778261, -119.4179324],
  },
  'US-CO': {
    name: 'Colorado',
    location: [39.5500507, -105.7820674],
  },
  'US-CT': {
    name: 'Connecticut',
    location: [41.6032207, -73.087749],
  },
  'US-DE': {
    name: 'Delaware',
    location: [38.9108325, -75.5276699],
  },
  'US-DC': {
    name: 'District of Columbia',
    location: [38.9071923, -77.0368707],
  },
  'US-FL': {
    name: 'Florida',
    location: [27.6648274, -81.5157535],
  },
  'US-GA': {
    name: 'Georgia',
    location: [32.1656221, -82.9000751],
  },
  'US-GU': {
    name: 'Guam',
    location: [13.444304, 144.793731],
  },
  'US-HI': {
    name: 'Hawaii',
    location: [19.8967662, -155.5827818],
  },
  'US-UM-84': {
    name: 'Howland Island',
    location: [0.8113219, -176.6182736],
  },
  'US-ID': {
    name: 'Idaho',
    location: [44.0682019, -114.7420408],
  },
  'US-IL': {
    name: 'Illinois',
    location: [40.6331249, -89.3985283],
  },
  'US-IN': {
    name: 'Indiana',
    location: [40.2671941, -86.1349019],
  },
  'US-IA': {
    name: 'Iowa',
    location: [41.8780025, -93.097702],
  },
  'US-UM-86': {
    name: 'Jarvis Island',
    location: [-0.3743503, -159.9967206],
  },
  'US-UM-67': {
    name: 'Johnston Atoll',
    location: [16.7295035, -169.5336477],
  },
  'US-KS': {
    name: 'Kansas',
    location: [39.011902, -98.4842465],
  },
  'US-KY': {
    name: 'Kentucky',
    location: [37.8393332, -84.2700179],
  },
  'US-UM-89': {
    name: 'Kingman Reef',
    location: [6.383333, -162.416667],
  },
  'US-LA': {
    name: 'Louisiana',
    location: [30.9842977, -91.9623327],
  },
  'US-ME': {
    name: 'Maine',
    location: [45.253783, -69.4454689],
  },
  'US-MD': {
    name: 'Maryland',
    location: [39.0457549, -76.6412712],
  },
  'US-MA': {
    name: 'Massachusetts',
    location: [42.4072107, -71.3824374],
  },
  'US-MI': {
    name: 'Michigan',
    location: [44.3148443, -85.6023643],
  },
  'US-UM-71': {
    name: 'Midway Atoll',
    location: [28.2072168, -177.3734926],
  },
  'US-MN': {
    name: 'Minnesota',
    location: [46.729553, -94.6858998],
  },
  'US-MS': {
    name: 'Mississippi',
    location: [32.3546679, -89.3985283],
  },
  'US-MO': {
    name: 'Missouri',
    location: [37.9642529, -91.8318334],
  },
  'US-MT': {
    name: 'Montana',
    location: [46.8796822, -110.3625658],
  },
  'US-UM-76': {
    name: 'Navassa Island',
    location: [18.4100689, -75.0114612],
  },
  'US-NE': {
    name: 'Nebraska',
    location: [41.4925374, -99.9018131],
  },
  'US-NV': {
    name: 'Nevada',
    location: [38.8026097, -116.419389],
  },
  'US-NH': {
    name: 'New Hampshire',
    location: [43.1938516, -71.5723953],
  },
  'US-NJ': {
    name: 'New Jersey',
    location: [40.0583238, -74.4056612],
  },
  'US-NM': {
    name: 'New Mexico',
    location: [34.5199402, -105.8700901],
  },
  'US-NY': {
    name: 'New York',
    location: [40.7127753, -74.0059728],
  },
  'US-NC': {
    name: 'North Carolina',
    location: [35.7595731, -79.0192997],
  },
  'US-ND': {
    name: 'North Dakota',
    location: [47.5514926, -101.0020119],
  },
  'US-MP': {
    name: 'Northern Mariana Islands',
    location: [15.0979, 145.6739],
  },
  'US-OH': {
    name: 'Ohio',
    location: [40.4172871, -82.907123],
  },
  'US-OK': {
    name: 'Oklahoma',
    location: [35.4675602, -97.5164276],
  },
  'US-OR': {
    name: 'Oregon',
    location: [43.8041334, -120.5542012],
  },
  'US-UM-95': {
    name: 'Palmyra Atoll',
    location: [5.8885026, -162.0786656],
  },
  'US-PA': {
    name: 'Pennsylvania',
    location: [41.2033216, -77.1945247],
  },
  'US-PR': {
    name: 'Puerto Rico',
    location: [18.220833, -66.590149],
  },
  'US-RI': {
    name: 'Rhode Island',
    location: [41.5800945, -71.4774291],
  },
  'US-SC': {
    name: 'South Carolina',
    location: [33.836081, -81.1637245],
  },
  'US-SD': {
    name: 'South Dakota',
    location: [43.9695148, -99.9018131],
  },
  'US-TN': {
    name: 'Tennessee',
    location: [35.5174913, -86.5804473],
  },
  'US-TX': {
    name: 'Texas',
    location: [31.9685988, -99.9018131],
  },
  'US-UM': {
    name: 'United States Minor Outlying Islands',
    location: [19.2823192, 166.647047],
  },
  'US-VI': {
    name: 'United States Virgin Islands',
    location: [18.335765, -64.896335],
  },
  'US-UT': {
    name: 'Utah',
    location: [39.3209801, -111.0937311],
  },
  'US-VT': {
    name: 'Vermont',
    location: [44.5588028, -72.5778415],
  },
  'US-VA': {
    name: 'Virginia',
    location: [37.4315734, -78.6568942],
  },
  'US-UM-79': {
    name: 'Wake Island',
    location: [19.279619, 166.6499348],
  },
  'US-WA': {
    name: 'Washington',
    location: [47.7510741, -120.7401385],
  },
  'US-WV': {
    name: 'West Virginia',
    location: [38.5976262, -80.4549026],
  },
  'US-WI': {
    name: 'Wisconsin',
    location: [43.7844397, -88.7878678],
  },
  'US-WY': {
    name: 'Wyoming',
    location: [43.0759678, -107.2902839],
  },
  'CA-AB': {
    name: 'Alberta',
    location: [53.9332706, -116.5765035],
  },
  'CA-BC': {
    name: 'British Columbia',
    location: [53.7266683, -127.6476205],
  },
  'CA-MB': {
    name: 'Manitoba',
    location: [53.7608608, -98.8138762],
  },
  'CA-NB': {
    name: 'New Brunswick',
    location: [46.5653163, -66.4619164],
  },
  'CA-NL': {
    name: 'Newfoundland and Labrador',
    location: [53.1355091, -57.6604364],
  },
  'CA-NT': {
    name: 'Northwest Territories',
    location: [64.8255441, -124.8457334],
  },
  'CA-NS': {
    name: 'Nova Scotia',
    location: [44.6819866, -63.744311],
  },
  'CA-NU': {
    name: 'Nunavut',
    location: [70.2997711, -83.107577],
  },
  'CA-ON': {
    name: 'Ontario',
    location: [51.253775, -85.323214],
  },
  'CA-PE': {
    name: 'Prince Edward Island',
    location: [46.510712, -63.4168136],
  },
  'CA-QC': {
    name: 'Quebec',
    location: [52.9399159, -73.5491361],
  },
  'CA-SK': {
    name: 'Saskatchewan',
    location: [52.9399159, -106.4508639],
  },
  'CA-YT': {
    name: 'Yukon',
    location: [35.5067215, -97.7625441],
  },
  'RU-ALT': {
    name: 'Altai Krai',
    location: [51.7936298, 82.6758596],
  },
  'RU-AL': {
    name: 'Altai Republic',
    location: [50.6181924, 86.2199308],
  },
  'RU-AMU': {
    name: 'Amur Oblast',
    location: [54.6035065, 127.4801721],
  },
  'RU-ARK': {
    name: 'Arkhangelsk',
    location: [64.5458549, 40.5505769],
  },
  'RU-AST': {
    name: 'Astrakhan Oblast',
    location: [46.1321166, 48.0610115],
  },
  'RU-BEL': {
    name: 'Belgorod Oblast',
    location: [50.7106926, 37.7533377],
  },
  'RU-BRY': {
    name: 'Bryansk Oblast',
    location: [53.0408599, 33.26909],
  },
  'RU-CE': {
    name: 'Chechen Republic',
    location: [43.4023301, 45.7187468],
  },
  'RU-CHE': {
    name: 'Chelyabinsk Oblast',
    location: [54.4319422, 60.8788963],
  },
  'RU-CHU': {
    name: 'Chukotka Autonomous Okrug',
    location: [65.6298355, 171.6952159],
  },
  'RU-CU': {
    name: 'Chuvash Republic',
    location: [55.5595992, 46.9283535],
  },
  'RU-IRK': {
    name: 'Irkutsk',
    location: [52.2854834, 104.2890222],
  },
  'RU-IVA': {
    name: 'Ivanovo Oblast',
    location: [57.1056854, 41.4830084],
  },
  'RU-YEV': {
    name: 'Jewish Autonomous Oblast',
    location: [48.4808147, 131.7657367],
  },
  'RU-KB': {
    name: 'Kabardino-Balkar Republic',
    location: [43.3932469, 43.5628498],
  },
  'RU-KGD': {
    name: 'Kaliningrad',
    location: [54.7104264, 20.4522144],
  },
  'RU-KLU': {
    name: 'Kaluga Oblast',
    location: [54.3872666, 35.1889094],
  },
  'RU-KAM': {
    name: 'Kamchatka Krai',
    location: [61.4343981, 166.7884131],
  },
  'RU-KC': {
    name: 'Karachay-Cherkess Republic',
    location: [43.8845143, 41.7303939],
  },
  'RU-KEM': {
    name: 'Kemerovo Oblast',
    location: [54.7574648, 87.4055288],
  },
  'RU-KHA': {
    name: 'Khabarovsk Krai',
    location: [50.5888431, 135],
  },
  'RU-KHM': {
    name: 'Khanty-Mansi Autonomous Okrug',
    location: [62.2287062, 70.6410057],
  },
  'RU-KIR': {
    name: 'Kirov Oblast',
    location: [58.4198529, 50.2097248],
  },
  'RU-KO': {
    name: 'Komi Republic',
    location: [63.8630539, 54.831269],
  },
  'RU-KOS': {
    name: 'Kostroma Oblast',
    location: [58.5501069, 43.9541102],
  },
  'RU-KDA': {
    name: 'Krasnodar Krai',
    location: [45.6415289, 39.7055977],
  },
  'RU-KYA': {
    name: 'Krasnoyarsk Krai',
    location: [64.2479758, 95.1104176],
  },
  'RU-KGN': {
    name: 'Kurgan Oblast',
    location: [55.4481548, 65.1180975],
  },
  'RU-KRS': {
    name: 'Kursk Oblast',
    location: [51.7634026, 35.3811812],
  },
  'RU-LEN': {
    name: 'Leningrad Oblast',
    location: [60.0793208, 31.8926645],
  },
  'RU-LIP': {
    name: 'Lipetsk Oblast',
    location: [52.5264702, 39.2032269],
  },
  'RU-MAG': {
    name: 'Magadan Oblast',
    location: [62.6643417, 153.914991],
  },
  'RU-ME': {
    name: 'Mari El Republic',
    location: [56.438457, 47.9607758],
  },
  'RU-MOW': {
    name: 'Moscow',
    location: [55.755826, 37.6172999],
  },
  'RU-MOS': {
    name: 'Moscow Oblast',
    location: [55.340396, 38.2917651],
  },
  'RU-MUR': {
    name: 'Murmansk Oblast',
    location: [67.8442674, 35.0884102],
  },
  'RU-NEN': {
    name: 'Nenets Autonomous Okrug',
    location: [67.6078337, 57.6338331],
  },
  'RU-NIZ': {
    name: 'Nizhny Novgorod Oblast',
    location: [55.7995159, 44.0296769],
  },
  'RU-NGR': {
    name: 'Novgorod Oblast',
    location: [58.2427552, 32.566519],
  },
  'RU-NVS': {
    name: 'Novosibirsk',
    location: [54.9832693, 82.8963831],
  },
  'RU-OMS': {
    name: 'Omsk Oblast',
    location: [55.0554669, 73.3167342],
  },
  'RU-ORE': {
    name: 'Orenburg Oblast',
    location: [51.7634026, 54.6188188],
  },
  'RU-ORL': {
    name: 'Oryol Oblast',
    location: [52.7856414, 36.9242344],
  },
  'RU-PNZ': {
    name: 'Penza Oblast',
    location: [53.1412105, 44.0940048],
  },
  'RU-PER': {
    name: 'Perm Krai',
    location: [58.8231929, 56.5872481],
  },
  'RU-PRI': {
    name: 'Primorsky Krai',
    location: [45.0525641, 135],
  },
  'RU-PSK': {
    name: 'Pskov Oblast',
    location: [56.7708599, 29.094009],
  },
  'RU-AD': {
    name: 'Republic of Adygea',
    location: [44.8229155, 40.1754463],
  },
  'RU-BA': {
    name: 'Republic of Bashkortostan',
    location: [54.2312172, 56.1645257],
  },
  'RU-BU': {
    name: 'Republic of Buryatia',
    location: [54.8331146, 112.406053],
  },
  'RU-DA': {
    name: 'Republic of Dagestan',
    location: [42.1431886, 47.0949799],
  },
  'RU-IN': {
    name: 'Republic of Ingushetia',
    location: [43.4051698, 44.8202999],
  },
  'RU-KL': {
    name: 'Republic of Kalmykia',
    location: [46.1867176, 45],
  },
  'RU-KR': {
    name: 'Republic of Karelia',
    location: [63.1558702, 32.9905552],
  },
  'RU-KK': {
    name: 'Republic of Khakassia',
    location: [53.0452281, 90.3982145],
  },
  'RU-MO': {
    name: 'Republic of Mordovia',
    location: [54.2369441, 44.068397],
  },
  'RU-SE': {
    name: 'Republic of North Ossetia-Alania',
    location: [43.0451302, 44.2870972],
  },
  'RU-TA': {
    name: 'Republic of Tatarstan',
    location: [55.1802364, 50.7263945],
  },
  'RU-ROS': {
    name: 'Rostov Oblast',
    location: [47.6853247, 41.8258952],
  },
  'RU-RYA': {
    name: 'Ryazan Oblast',
    location: [54.3875964, 41.2595661],
  },
  'RU-SPE': {
    name: 'Saint Petersburg',
    location: [59.9310584, 30.3609096],
  },
  'RU-SA': {
    name: 'Sakha Republic',
    location: [66.7613451, 124.123753],
  },
  'RU-SAK': {
    name: 'Sakhalin',
    location: [50.6909848, 142.9505689],
  },
  'RU-SAM': {
    name: 'Samara Oblast',
    location: [53.4183839, 50.4725528],
  },
  'RU-SAR': {
    name: 'Saratov Oblast',
    location: [51.8369263, 46.7539397],
  },
  'RU-UA-40': {
    name: 'Sevastopol',
    location: [44.61665, 33.5253671],
  },
  'RU-SMO': {
    name: 'Smolensk Oblast',
    location: [54.9882994, 32.6677378],
  },
  'RU-STA': {
    name: 'Stavropol Krai',
    location: [44.6680993, 43.520214],
  },
  'RU-SVE': {
    name: 'Sverdlovsk',
    location: [56.8430993, 60.6454086],
  },
  'RU-TAM': {
    name: 'Tambov Oblast',
    location: [52.6416589, 41.4216451],
  },
  'RU-TOM': {
    name: 'Tomsk Oblast',
    location: [58.8969882, 82.67655],
  },
  'RU-TUL': {
    name: 'Tula Oblast',
    location: [54.163768, 37.5649507],
  },
  'RU-TY': {
    name: 'Tuva Republic',
    location: [51.8872669, 95.6260172],
  },
  'RU-TVE': {
    name: 'Tver Oblast',
    location: [57.0021654, 33.9853142],
  },
  'RU-TYU': {
    name: 'Tyumen Oblast',
    location: [56.9634387, 66.948278],
  },
  'RU-UD': {
    name: 'Udmurt Republic',
    location: [57.0670218, 53.0277948],
  },
  'RU-ULY': {
    name: 'Ulyanovsk Oblast',
    location: [53.9793357, 47.7762425],
  },
  'RU-VLA': {
    name: 'Vladimir Oblast',
    location: [56.1553465, 40.5926685],
  },
  'RU-VGG': {
    name: 'Volgograd Oblast',
    location: [49.2587393, 39.8154463],
  },
  'RU-VLG': {
    name: 'Vologda Oblast',
    location: [59.8706711, 40.6555411],
  },
  'RU-VOR': {
    name: 'Voronezh Oblast',
    location: [50.8589713, 39.8644374],
  },
  'RU-YAN': {
    name: 'Yamalo-Nenets Autonomous Okrug',
    location: [66.0653057, 76.9345193],
  },
  'RU-YAR': {
    name: 'Yaroslavl Oblast',
    location: [57.8991523, 38.8388633],
  },
  'RU-ZAB': {
    name: 'Zabaykalsky Krai',
    location: [53.0928771, 116.9676561],
  },
  'AU-ACT': {
    name: 'Australian Capital Territory',
    location: [-35.4734679, 149.0123679],
  },
  'AU-NSW': {
    name: 'New South Wales',
    location: [-31.2532183, 146.921099],
  },
  'AU-NT': {
    name: 'Northern Territory',
    location: [-19.4914108, 132.5509603],
  },
  'AU-QLD': {
    name: 'Queensland',
    location: [-20.9175738, 142.7027956],
  },
  'AU-SA': {
    name: 'South Australia',
    location: [-30.0002315, 136.2091547],
  },
  'AU-TAS': {
    name: 'Tasmania',
    location: [-41.4545196, 145.9706647],
  },
  'AU-VIC': {
    name: 'Victoria',
    location: [-36.4856423, 140.9779425],
  },
  'AU-WA': {
    name: 'Western Australia',
    location: [-27.6728168, 121.6283098],
  },
  'BR-AC': {
    name: 'Acre',
    location: [-9.023796, -70.811995],
  },
  'BR-AL': {
    name: 'Alagoas',
    location: [-9.5713058, -36.7819505],
  },
  'BR-AP': {
    name: 'Amapá',
    location: [0.9019925, -52.0029565],
  },
  'BR-AM': {
    name: 'Amazonas',
    location: [-3.07, -61.66],
  },
  'BR-BA': {
    name: 'Bahia',
    location: [-11.409874, -41.280857],
  },
  'BR-CE': {
    name: 'Ceará',
    location: [-5.4983977, -39.3206241],
  },
  'BR-DF': {
    name: 'Distrito Federal',
    location: [-15.7997654, -47.8644715],
  },
  'BR-ES': {
    name: 'Espírito Santo',
    location: [-19.1834229, -40.3088626],
  },
  'BR-GO': {
    name: 'Goiás',
    location: [-15.8270369, -49.8362237],
  },
  'BR-MA': {
    name: 'Maranhão',
    location: [-4.9609498, -45.2744159],
  },
  'BR-MT': {
    name: 'Mato Grosso',
    location: [-12.6818712, -56.921099],
  },
  'BR-MS': {
    name: 'Mato Grosso do Sul',
    location: [-20.7722295, -54.7851531],
  },
  'BR-MG': {
    name: 'Minas Gerais',
    location: [-18.512178, -44.5550308],
  },
  'BR-PR': {
    name: 'Paraná',
    location: [-25.2520888, -52.0215415],
  },
  'BR-PB': {
    name: 'Paraíba',
    location: [-7.2399609, -36.7819505],
  },
  'BR-PA': {
    name: 'Pará',
    location: [-1.9981271, -54.9306152],
  },
  'BR-PE': {
    name: 'Pernambuco',
    location: [-8.8137173, -36.954107],
  },
  'BR-PI': {
    name: 'Piauí',
    location: [-7.7183401, -42.7289236],
  },
  'BR-RN': {
    name: 'Rio Grande do Norte',
    location: [-5.4025803, -36.954107],
  },
  'BR-RS': {
    name: 'Rio Grande do Sul',
    location: [-30.0346316, -51.2176986],
  },
  'BR-RJ': {
    name: 'Rio de Janeiro',
    location: [-22.9068467, -43.1728965],
  },
  'BR-RO': {
    name: 'Rondônia',
    location: [-11.5057341, -63.580611],
  },
  'BR-RR': {
    name: 'Roraima',
    location: [2.7375971, -62.0750998],
  },
  'BR-SC': {
    name: 'Santa Catarina',
    location: [-27.33, -49.44],
  },
  'BR-SE': {
    name: 'Sergipe',
    location: [-10.5740934, -37.3856581],
  },
  'BR-SP': {
    name: 'São Paulo',
    location: [-23.5505199, -46.6333094],
  },
  'BR-TO': {
    name: 'Tocantins',
    location: [-10.17528, -48.2982474],
  },
  'IN-AN': {
    name: 'Andaman and Nicobar Islands',
    location: [11.7400867, 92.6586401],
  },
  'IN-AP': {
    name: 'Andhra Pradesh',
    location: [15.9128998, 79.7399875],
  },
  'IN-AR': {
    name: 'Arunachal Pradesh',
    location: [28.2179994, 94.7277528],
  },
  'IN-AS': {
    name: 'Assam',
    location: [26.2006043, 92.9375739],
  },
  'IN-BR': {
    name: 'Bihar',
    location: [25.0960742, 85.3131194],
  },
  'IN-CH': {
    name: 'Chandigarh',
    location: [30.7333148, 76.7794179],
  },
  'IN-CT': {
    name: 'Chhattisgarh',
    location: [21.2786567, 81.8661442],
  },
  'IN-DH': {
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    location: [20.3973736, 72.8327991],
  },
  'IN-DL': {
    name: 'Delhi',
    location: [28.7040592, 77.1024902],
  },
  'IN-GA': {
    name: 'Goa',
    location: [15.2993265, 74.123996],
  },
  'IN-GJ': {
    name: 'Gujarat',
    location: [22.258652, 71.1923805],
  },
  'IN-HR': {
    name: 'Haryana',
    location: [29.0587757, 76.085601],
  },
  'IN-HP': {
    name: 'Himachal Pradesh',
    location: [31.1048294, 77.1733901],
  },
  'IN-JK': {
    name: 'Jammu and Kashmir',
    location: [33.277839, 75.3412179],
  },
  'IN-JH': {
    name: 'Jharkhand',
    location: [23.6101808, 85.2799354],
  },
  'IN-KA': {
    name: 'Karnataka',
    location: [15.3172775, 75.7138884],
  },
  'IN-KL': {
    name: 'Kerala',
    location: [10.8505159, 76.2710833],
  },
  'IN-LA': {
    name: 'Ladakh',
    location: [34.2268475, 77.5619419],
  },
  'IN-LD': {
    name: 'Lakshadweep',
    location: [10.3280265, 72.7846336],
  },
  'IN-MP': {
    name: 'Madhya Pradesh',
    location: [22.9734229, 78.6568942],
  },
  'IN-MH': {
    name: 'Maharashtra',
    location: [19.7514798, 75.7138884],
  },
  'IN-MN': {
    name: 'Manipur',
    location: [24.6637173, 93.9062688],
  },
  'IN-ML': {
    name: 'Meghalaya',
    location: [25.4670308, 91.366216],
  },
  'IN-MZ': {
    name: 'Mizoram',
    location: [23.164543, 92.9375739],
  },
  'IN-NL': {
    name: 'Nagaland',
    location: [26.1584354, 94.5624426],
  },
  'IN-OR': {
    name: 'Odisha',
    location: [20.9516658, 85.0985236],
  },
  'IN-PY': {
    name: 'Puducherry',
    location: [11.9415915, 79.8083133],
  },
  'IN-PB': {
    name: 'Punjab',
    location: [31.1471305, 75.3412179],
  },
  'IN-RJ': {
    name: 'Rajasthan',
    location: [27.0238036, 74.2179326],
  },
  'IN-SK': {
    name: 'Sikkim',
    location: [27.5329718, 88.5122178],
  },
  'IN-TN': {
    name: 'Tamil Nadu',
    location: [11.1271225, 78.6568942],
  },
  'IN-TG': {
    name: 'Telangana',
    location: [18.1124372, 79.0192997],
  },
  'IN-TR': {
    name: 'Tripura',
    location: [23.9408482, 91.9881527],
  },
  'IN-UP': {
    name: 'Uttar Pradesh',
    location: [26.8467088, 80.9461592],
  },
  'IN-UT': {
    name: 'Uttarakhand',
    location: [30.066753, 79.0192997],
  },
  'IN-WB': {
    name: 'West Bengal',
    location: [22.9867569, 87.8549755],
  },
  'ID-AC': {
    name: 'Aceh',
    location: [4.695135, 96.7493993],
  },
  'ID-BA': {
    name: 'Bali',
    location: [-8.3405389, 115.0919509],
  },
  'ID-BT': {
    name: 'Banten',
    location: [-6.4058172, 106.0640179],
  },
  'ID-BE': {
    name: 'Bengkulu',
    location: [-3.7928451, 102.2607641],
  },
  'ID-YO': {
    name: 'DI Yogyakarta',
    location: [-7.8753849, 110.4262088],
  },
  'ID-JK': {
    name: 'DKI Jakarta',
    location: [-6.2087634, 106.845599],
  },
  'ID-GO': {
    name: 'Gorontalo',
    location: [0.5435442, 123.0567693],
  },
  'ID-JA': {
    name: 'Jambi',
    location: [-1.6101229, 103.6131203],
  },
  'ID-JB': {
    name: 'Jawa Barat',
    location: [-7.090911, 107.668887],
  },
  'ID-JT': {
    name: 'Jawa Tengah',
    location: [-7.150975, 110.1402594],
  },
  'ID-JI': {
    name: 'Jawa Timur',
    location: [-7.5360639, 112.2384017],
  },
  'ID-KA': {
    name: 'Kalimantan Barat',
    location: [0.9618834, 114.5548495],
  },
  'ID-KS': {
    name: 'Kalimantan Selatan',
    location: [-3.0926415, 115.2837585],
  },
  'ID-KT': {
    name: 'Kalimantan Tengah',
    location: [-1.6814878, 113.3823545],
  },
  'ID-KI': {
    name: 'Kalimantan Timur',
    location: [0.5386586, 116.419389],
  },
  'ID-KU': {
    name: 'Kalimantan Utara',
    location: [3.0730929, 116.0413889],
  },
  'ID-BB': {
    name: 'Kepulauan Bangka Belitung',
    location: [-2.7410513, 106.4405872],
  },
  'ID-KR': {
    name: 'Kepulauan Riau',
    location: [3.9456514, 108.1428669],
  },
  'ID-LA': {
    name: 'Lampung',
    location: [-4.5585849, 105.4068079],
  },
  'ID-MA': {
    name: 'Maluku',
    location: [-3.2384616, 130.1452734],
  },
  'ID-MU': {
    name: 'Maluku Utara',
    location: [1.5709993, 127.8087693],
  },
  'ID-NB': {
    name: 'Nusa Tenggara Barat',
    location: [-8.6529334, 117.3616476],
  },
  'ID-NT': {
    name: 'Nusa Tenggara Timur',
    location: [-8.6573819, 121.0793705],
  },
  'ID-PA': {
    name: 'Papua',
    location: [-5.0122202, 141.3470159],
  },
  'ID-PB': {
    name: 'Papua Barat',
    location: [-1.3361154, 133.1747162],
  },
  'ID-RI': {
    name: 'Riau',
    location: [0.2933469, 101.7068294],
  },
  'ID-SR': {
    name: 'Sulawesi Barat',
    location: [-2.8441371, 119.2320784],
  },
  'ID-SN': {
    name: 'Sulawesi Selatan',
    location: [-3.6687994, 119.9740534],
  },
  'ID-ST': {
    name: 'Sulawesi Tengah',
    location: [-1.4300254, 121.4456179],
  },
  'ID-SG': {
    name: 'Sulawesi Tenggara',
    location: [-4.14491, 122.174605],
  },
  'ID-SA': {
    name: 'Sulawesi Utara',
    location: [0.6246932, 123.9750018],
  },
  'ID-SB': {
    name: 'Sumatera Barat',
    location: [-0.7399397, 100.8000051],
  },
  'ID-SS': {
    name: 'Sumatera Selatan',
    location: [-3.3194374, 103.914399],
  },
  'ID-SU': {
    name: 'Sumatera Utara',
    location: [2.1153547, 99.5450974],
  },
} as const
