export const STEP = {
  SELECT_TYPE: 'SELECT_TYPE',
  SETUP_DOMAIN: 'SETUP_DOMAIN',
  SETUP_INFO: 'SETUP_INFO',
  SETUP_EXTRA: 'SETUP_EXTRA',
  FINISHED: 'FINISHED',
} as const

export const COMMUNITY_TYPE = {
  PRODUCT: 'PRODUCT',
  GAMING: 'GAMING',
  TEACH: 'TEACH',
  GROUP: 'GROUP',
} as const
