import type { TSourceNode, TSourceTree, TSourceWorkspace } from '../../contracts'
import { loadDocuments, type TDocumentMetadata } from '../documentFile'
import { asRecord, linkNode, pageNode, scopeNode, sectionNode } from '../helpers'
import { parseStaticConfig } from '../staticConfig'

const titleize = (value: string): string =>
  value
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase())

const findDocument = (
  id: string,
  documents: Map<string, TDocumentMetadata>,
): TDocumentMetadata | undefined =>
  documents.get(`docs/${id}.md`) ??
  documents.get(`docs/${id}.mdx`) ??
  documents.get(`docs/${id}/index.md`)

const documentPage = (document: TDocumentMetadata, id: string, title?: string) => ({
  ...pageNode(document, title),
  route:
    typeof document.frontmatter.slug === 'string' && document.frontmatter.slug.startsWith('/')
      ? document.frontmatter.slug
      : `/${id}`,
})

const items = (
  values: unknown,
  scopeId: string,
  documents: Map<string, TDocumentMetadata>,
): TSourceNode[] =>
  (Array.isArray(values) ? values : []).flatMap((value): TSourceNode[] => {
    if (typeof value === 'string') {
      const document = findDocument(value, documents)
      return document ? [documentPage(document, value)] : []
    }
    const item = asRecord(value)
    if (!item) return []
    if (item.type === 'link' && typeof item.href === 'string') {
      return [linkNode(String(item.label || item.href), item.href)]
    }
    if (item.type === 'autogenerated' && typeof item.dirName === 'string') {
      return Array.from(documents.values())
        .filter((document) => document.sourcePath.startsWith(`docs/${item.dirName}/`))
        .sort(
          (a, b) =>
            Number(a.frontmatter.sidebar_position ?? 0) -
            Number(b.frontmatter.sidebar_position ?? 0),
        )
        .map((document) =>
          documentPage(document, document.sourcePath.replace(/^docs\//, '').replace(/\.mdx?$/, '')),
        )
    }
    if (item.type === 'doc' && typeof item.id === 'string') {
      const document = findDocument(item.id, documents)
      return document
        ? [documentPage(document, item.id, typeof item.label === 'string' ? item.label : undefined)]
        : []
    }
    if (item.type === 'category') {
      const children: TSourceNode[] = []
      const link = asRecord(item.link)
      if (link?.type === 'doc' && typeof link.id === 'string') {
        const document = findDocument(link.id, documents)
        if (document) children.push(documentPage(document, link.id))
      }
      children.push(...items(item.items, scopeId, documents))
      return [
        sectionNode(`category:${String(item.label).toLowerCase()}`, String(item.label), children),
      ]
    }
    return []
  })

/** Maps Docusaurus sidebars and doc frontmatter into canonical SourceTree semantics.
 *
 * @see docs/bulk-import/bulk-import.md
 */
export const analyzeDocusaurus = async (workspace: TSourceWorkspace): Promise<TSourceTree> => {
  const configPaths = workspace.files
    .map((file) => file.path)
    .filter((file) => /^(docusaurus\.config|sidebars)\.(?:js|ts)$/.test(file))
  const sidebarPath = configPaths.find((file) => file.startsWith('sidebars.'))!
  const sidebar = asRecord(parseStaticConfig(await workspace.readText(sidebarPath), sidebarPath))
  const documents = await loadDocuments(workspace, 'docs')

  return {
    navigation: Object.entries(sidebar ?? {}).map(([scopeId, value]) =>
      scopeNode(`sidebar:${scopeId}`, titleize(scopeId), '/', items(value, scopeId, documents)),
    ),
    schemaVersion: 1,
    source: { configPaths, framework: 'docusaurus', root: 'docs' },
  }
}
