defmodule GroupherServer.CMS.ContentImport.Threads.Doc.Frameworks.DocusaurusTest do
  use GroupherServer.CMS.ContentImport.FrameworkCase, async: true

  alias GroupherServer.CMS.ContentImport.Threads.Doc.Frameworks.Docusaurus

  test "reads explicit and autogenerated sidebars" do
    root = fixture("docusaurus/basic")

    assert {:ok, %{tree: tree, diagnostics: []}} = Docusaurus.parse(root)

    assert tree["source"] == %{
             "framework" => "docusaurus",
             "root" => "docs",
             "configPaths" => ["docusaurus.config.ts", "sidebars.ts"]
           }

    [tutorial, api] = tree["navigation"]
    assert tutorial["title"] == "Tutorial Sidebar"

    assert Enum.map(tutorial["children"], &{&1["kind"], &1["title"]}) == [
             {"page", "Introduction"},
             {"section", "Guides"},
             {"link", "Project"}
           ]

    assert hd(tutorial["children"])["route"] == "/welcome"

    [guide_index, guide] = tutorial["children"] |> Enum.at(1) |> Map.fetch!("children")
    assert guide_index["sourcePath"] == "docs/guide/index.md"
    assert guide["sourcePath"] == "docs/guide/start.md"
    assert api["children"] |> Enum.map(& &1["title"]) == ["Overview", "Client"]
  end

  test "reports a missing sidebar page without inventing sourcePath" do
    root =
      Path.join(System.tmp_dir!(), "docusaurus-missing-#{System.unique_integer([:positive])}")

    on_exit(fn -> File.rm_rf(root) end)
    File.mkdir_p!(Path.join(root, "docs"))
    File.write!(Path.join(root, "docusaurus.config.ts"), "export default {}")
    File.write!(Path.join(root, "sidebars.ts"), "export default {docs: ['missing']}")

    assert {:ok, %{tree: tree, diagnostics: [diagnostic]}} = Docusaurus.parse(root)
    assert diagnostic.code == "page_not_found"
    assert diagnostic.source_id == "missing"
    assert tree["navigation"] |> hd() |> Map.fetch!("children") == []
  end
end
