defmodule GroupherServer.CMS.ContentImport.Threads.Doc.Frameworks.StarlightTest do
  use GroupherServer.CMS.ContentImport.FrameworkCase, async: true

  alias GroupherServer.CMS.ContentImport.Threads.Doc.Frameworks.Starlight

  test "reads explicit, nested and autogenerated sidebar entries" do
    root = fixture("starlight/basic")

    assert {:ok, %{tree: tree, diagnostics: []}} = Starlight.parse(root)

    assert tree["source"] == %{
             "framework" => "starlight",
             "root" => "src/content/docs",
             "configPaths" => ["astro.config.mjs"]
           }

    [scope] = tree["navigation"]

    assert Enum.map(scope["children"], &{&1["kind"], &1["title"]}) == [
             {"page", "Home"},
             {"section", "Guides"},
             {"section", "API"},
             {"link", "Project"}
           ]

    [start, advanced] = scope["children"] |> Enum.at(1) |> Map.fetch!("children")
    assert start["title"] == "Getting Started"
    assert advanced["sourcePath"] == "src/content/docs/guides/advanced.mdx"
  end

  test "reports a missing sidebar page without crashing" do
    root = Path.join(System.tmp_dir!(), "starlight-missing-#{System.unique_integer([:positive])}")
    on_exit(fn -> File.rm_rf(root) end)
    File.mkdir_p!(Path.join(root, "src/content/docs"))

    File.write!(
      Path.join(root, "astro.config.mjs"),
      "import starlight from '@astrojs/starlight'; starlight({sidebar: [{label: 'Missing', slug: 'missing'}]})"
    )

    assert {:ok, %{tree: tree, diagnostics: [diagnostic]}} = Starlight.parse(root)
    assert diagnostic.code == "page_not_found"
    assert diagnostic.source_id == "missing"
    assert tree["navigation"] |> hd() |> Map.fetch!("children") == []
  end
end
