import { WALLPAPER_TEXTURE } from '../constant'
import { ASCII_SHADER_BRANCH, ASCII_SHADER_HELPER, ASCII_WEBGL_ID } from './ascii'
import { BEAM_SHADER_BRANCH, BEAM_WEBGL_ID } from './beam'
import { DOTS_SHADER_BRANCH, DOTS_WEBGL_ID } from './dots'
import { NOISE_SHADER_BRANCH, NOISE_WEBGL_ID } from './noise'
import { OIL_SHADER_BRANCH, OIL_SHADER_HELPER, OIL_WEBGL_ID } from './oil'
import { TILE_SHADER_BRANCH, TILE_SHADER_UV, TILE_WEBGL_ID } from './tile'

export const TEXTURE_TYPE = {
  [WALLPAPER_TEXTURE.NOISE]: NOISE_WEBGL_ID,
  [WALLPAPER_TEXTURE.TILE]: TILE_WEBGL_ID,
  [WALLPAPER_TEXTURE.BEAM]: BEAM_WEBGL_ID,
  [WALLPAPER_TEXTURE.ASCII]: ASCII_WEBGL_ID,
  [WALLPAPER_TEXTURE.DOTS]: DOTS_WEBGL_ID,
  [WALLPAPER_TEXTURE.OIL]: OIL_WEBGL_ID,
} as const

export const TEXTURE_SHADER_HELPERS = [ASCII_SHADER_HELPER, OIL_SHADER_HELPER].join('\n')

export const TEXTURE_SHADER_UV = TILE_SHADER_UV

export const TEXTURE_SHADER_BRANCHES = [
  TILE_SHADER_BRANCH,
  BEAM_SHADER_BRANCH,
  ASCII_SHADER_BRANCH,
  NOISE_SHADER_BRANCH,
  DOTS_SHADER_BRANCH,
  OIL_SHADER_BRANCH,
].join('\n')
