import { DITHER_SHADER_BRANCH, DITHER_SHADER_HELPER, DITHER_WEBGL_ID } from './dither'
import { NOISE_SHADER_BRANCH, NOISE_WEBGL_ID } from './noise'
import { PIXELATE_SHADER_BRANCH, PIXELATE_SHADER_UV, PIXELATE_WEBGL_ID } from './pixelate'
import { SCREENTONE_SHADER_BRANCH, SCREENTONE_WEBGL_ID } from './screentone'

export const TEXTURE_TYPE = {
  noise: NOISE_WEBGL_ID,
  pixelate: PIXELATE_WEBGL_ID,
  screentone: SCREENTONE_WEBGL_ID,
  dither: DITHER_WEBGL_ID,
} as const

export const TEXTURE_SHADER_HELPERS = DITHER_SHADER_HELPER

export const TEXTURE_SHADER_UV = PIXELATE_SHADER_UV

export const TEXTURE_SHADER_BRANCHES = [
  PIXELATE_SHADER_BRANCH,
  NOISE_SHADER_BRANCH,
  SCREENTONE_SHADER_BRANCH,
  DITHER_SHADER_BRANCH,
].join('\n')
