import { ASCII_SHADER_BRANCH, ASCII_SHADER_HELPER, ASCII_WEBGL_ID } from './ascii'
import { BEAM_SHADER_BRANCH, BEAM_WEBGL_ID } from './beam'
import { NOISE_SHADER_BRANCH, NOISE_WEBGL_ID } from './noise'
import { PIXELATE_SHADER_BRANCH, PIXELATE_SHADER_UV, PIXELATE_WEBGL_ID } from './pixelate'
import { SCREENTONE_SHADER_BRANCH, SCREENTONE_WEBGL_ID } from './screentone'

export const TEXTURE_TYPE = {
  noise: NOISE_WEBGL_ID,
  pixelate: PIXELATE_WEBGL_ID,
  beam: BEAM_WEBGL_ID,
  ascii: ASCII_WEBGL_ID,
  screentone: SCREENTONE_WEBGL_ID,
} as const

export const TEXTURE_SHADER_HELPERS = ASCII_SHADER_HELPER

export const TEXTURE_SHADER_UV = PIXELATE_SHADER_UV

export const TEXTURE_SHADER_BRANCHES = [
  PIXELATE_SHADER_BRANCH,
  BEAM_SHADER_BRANCH,
  ASCII_SHADER_BRANCH,
  NOISE_SHADER_BRANCH,
  SCREENTONE_SHADER_BRANCH,
].join('\n')
