export const PAYMENT_USAGE = {
  SENIOR: 'SENIOR',
  GIRLS_CODE_TOO_PLAN: 'GIRLS_CODE_TOO_PLAN',
  DONATE: 'DONATE',
  SPONSOR: 'SPONSOR',
} as const

export const PAYMENT_METHOD = {
  ALIPAY: 'ALIPAY',
  WECHAT: 'WECHAT',
} as const
