import type { TWallpaper } from '~/spec'

/*
 * This file is generated by scripts/sync-wallpaper-assets.mjs.
 *
 * Mechanism:
 * - Every non-WebP image file placed in frontend/core/assets/wallpaper/picture
 *   is converted to WebP and included. Existing WebP files are treated as
 *   already compressed and are only size-checked.
 * - The wallpaper source key is the WebP file stem. If multiple source files
 *   share the same stem, the original extension is appended before conversion
 *   to avoid overwriting entries.
 * - Non-WebP source images are compressed into
 *   frontend/core/assets/wallpaper/picture and the script fails if a picture
 *   cannot be compressed under 500KB. Existing WebP pictures must already be
 *   under 500KB.
 * - Moving a file out of picture/ is the way to remove it from the picker.
 * - Each picture must have a matching file with the same filename in
 *   frontend/core/assets/wallpaper/picture-preview. The script creates missing
 *   previews before writing this manifest and fails if a preview cannot be
 *   compressed under 50KB.
 * - Picker cards must render preview, while the actual selected wallpaper renders image.
 *
 * Do not edit this file by hand; edit the assets folder and run yarn sync:wallpaper.
 */
export const PATTERN_WALLPAPER = {
  'backiee-1': {
    image: '/wallpaper/picture/backiee-1.webp',
    preview: '/wallpaper/picture-preview/backiee-1.webp',
  },
  'backiee-10': {
    image: '/wallpaper/picture/backiee-10.webp',
    preview: '/wallpaper/picture-preview/backiee-10.webp',
  },
  'backiee-11': {
    image: '/wallpaper/picture/backiee-11.webp',
    preview: '/wallpaper/picture-preview/backiee-11.webp',
  },
  'backiee-12': {
    image: '/wallpaper/picture/backiee-12.webp',
    preview: '/wallpaper/picture-preview/backiee-12.webp',
  },
  'backiee-13': {
    image: '/wallpaper/picture/backiee-13.webp',
    preview: '/wallpaper/picture-preview/backiee-13.webp',
  },
  'backiee-14': {
    image: '/wallpaper/picture/backiee-14.webp',
    preview: '/wallpaper/picture-preview/backiee-14.webp',
  },
  'backiee-15': {
    image: '/wallpaper/picture/backiee-15.webp',
    preview: '/wallpaper/picture-preview/backiee-15.webp',
  },
  'backiee-16': {
    image: '/wallpaper/picture/backiee-16.webp',
    preview: '/wallpaper/picture-preview/backiee-16.webp',
  },
  'backiee-17': {
    image: '/wallpaper/picture/backiee-17.webp',
    preview: '/wallpaper/picture-preview/backiee-17.webp',
  },
  'backiee-18': {
    image: '/wallpaper/picture/backiee-18.webp',
    preview: '/wallpaper/picture-preview/backiee-18.webp',
  },
  'backiee-19': {
    image: '/wallpaper/picture/backiee-19.webp',
    preview: '/wallpaper/picture-preview/backiee-19.webp',
  },
  'backiee-2': {
    image: '/wallpaper/picture/backiee-2.webp',
    preview: '/wallpaper/picture-preview/backiee-2.webp',
  },
  'backiee-3': {
    image: '/wallpaper/picture/backiee-3.webp',
    preview: '/wallpaper/picture-preview/backiee-3.webp',
  },
  'backiee-4': {
    image: '/wallpaper/picture/backiee-4.webp',
    preview: '/wallpaper/picture-preview/backiee-4.webp',
  },
  'backiee-5': {
    image: '/wallpaper/picture/backiee-5.webp',
    preview: '/wallpaper/picture-preview/backiee-5.webp',
  },
  'backiee-6': {
    image: '/wallpaper/picture/backiee-6.webp',
    preview: '/wallpaper/picture-preview/backiee-6.webp',
  },
  'backiee-7': {
    image: '/wallpaper/picture/backiee-7.webp',
    preview: '/wallpaper/picture-preview/backiee-7.webp',
  },
  'backiee-8': {
    image: '/wallpaper/picture/backiee-8.webp',
    preview: '/wallpaper/picture-preview/backiee-8.webp',
  },
  'backiee-9': {
    image: '/wallpaper/picture/backiee-9.webp',
    preview: '/wallpaper/picture-preview/backiee-9.webp',
  },
  mp_teal: {
    image: '/wallpaper/picture/mp_teal.webp',
    preview: '/wallpaper/picture-preview/mp_teal.webp',
  },
  ms: {
    image: '/wallpaper/picture/ms.webp',
    preview: '/wallpaper/picture-preview/ms.webp',
  },
  'openscreen-wallpaper13': {
    image: '/wallpaper/picture/openscreen-wallpaper13.webp',
    preview: '/wallpaper/picture-preview/openscreen-wallpaper13.webp',
  },
  'openscreen-wallpaper14': {
    image: '/wallpaper/picture/openscreen-wallpaper14.webp',
    preview: '/wallpaper/picture-preview/openscreen-wallpaper14.webp',
  },
  'openscreen-wallpaper18': {
    image: '/wallpaper/picture/openscreen-wallpaper18.webp',
    preview: '/wallpaper/picture-preview/openscreen-wallpaper18.webp',
  },
  'recordly-luisdelrio': {
    image: '/wallpaper/picture/recordly-luisdelrio.webp',
    preview: '/wallpaper/picture-preview/recordly-luisdelrio.webp',
  },
} satisfies Record<string, TWallpaper>
