import type { TWallpaper, TWallpaperPattern } from '~/spec'

/*
 * This file is generated by scripts/sync-wallpaper-assets.mjs.
 *
 * Mechanism:
 * - Every non-WebP image file placed in frontend/core/assets/wallpaper/picture
 *   is converted to WebP and included. Existing WebP files are treated as
 *   already compressed and are only size-checked.
 * - The wallpaper source key is the WebP file stem. If multiple source files
 *   share the same stem, the original extension is appended before conversion
 *   to avoid overwriting entries.
 * - Non-WebP source images are compressed into
 *   frontend/core/assets/wallpaper/picture and the script fails if a picture
 *   cannot be compressed under 500KB. Existing WebP pictures must already be
 *   under 500KB.
 * - Moving a file out of picture/ is the way to remove it from the picker.
 * - Each picture must have a matching file with the same filename in
 *   frontend/core/assets/wallpaper/picture-preview. The script creates missing
 *   previews before writing this manifest and fails if a preview cannot be
 *   compressed under 50KB.
 * - Picker cards must render preview, while the actual selected wallpaper renders image.
 * - SVG files in frontend/core/assets/wallpaper/pattern are rendered to
 *   compressed PNG files and exposed through WALLPAPER_PATTERN. Runtime apps
 *   receive only the PNG pattern files.
 *
 * Do not edit this file by hand; edit the assets folder and run yarn sync:wallpaper.
 */
export const PATTERN_WALLPAPER = {
  'backiee-1': {
    image: '/wallpaper/picture/backiee-1.webp',
    preview: '/wallpaper/picture-preview/backiee-1.webp',
  },
  'backiee-10': {
    image: '/wallpaper/picture/backiee-10.webp',
    preview: '/wallpaper/picture-preview/backiee-10.webp',
  },
  'backiee-11': {
    image: '/wallpaper/picture/backiee-11.webp',
    preview: '/wallpaper/picture-preview/backiee-11.webp',
  },
  'backiee-12': {
    image: '/wallpaper/picture/backiee-12.webp',
    preview: '/wallpaper/picture-preview/backiee-12.webp',
  },
  'backiee-13': {
    image: '/wallpaper/picture/backiee-13.webp',
    preview: '/wallpaper/picture-preview/backiee-13.webp',
  },
  'backiee-14': {
    image: '/wallpaper/picture/backiee-14.webp',
    preview: '/wallpaper/picture-preview/backiee-14.webp',
  },
  'backiee-15': {
    image: '/wallpaper/picture/backiee-15.webp',
    preview: '/wallpaper/picture-preview/backiee-15.webp',
  },
  'backiee-16': {
    image: '/wallpaper/picture/backiee-16.webp',
    preview: '/wallpaper/picture-preview/backiee-16.webp',
  },
  'backiee-17': {
    image: '/wallpaper/picture/backiee-17.webp',
    preview: '/wallpaper/picture-preview/backiee-17.webp',
  },
  'backiee-18': {
    image: '/wallpaper/picture/backiee-18.webp',
    preview: '/wallpaper/picture-preview/backiee-18.webp',
  },
  'backiee-19': {
    image: '/wallpaper/picture/backiee-19.webp',
    preview: '/wallpaper/picture-preview/backiee-19.webp',
  },
  'backiee-2': {
    image: '/wallpaper/picture/backiee-2.webp',
    preview: '/wallpaper/picture-preview/backiee-2.webp',
  },
  'backiee-3': {
    image: '/wallpaper/picture/backiee-3.webp',
    preview: '/wallpaper/picture-preview/backiee-3.webp',
  },
  'backiee-4': {
    image: '/wallpaper/picture/backiee-4.webp',
    preview: '/wallpaper/picture-preview/backiee-4.webp',
  },
  'backiee-5': {
    image: '/wallpaper/picture/backiee-5.webp',
    preview: '/wallpaper/picture-preview/backiee-5.webp',
  },
  'backiee-6': {
    image: '/wallpaper/picture/backiee-6.webp',
    preview: '/wallpaper/picture-preview/backiee-6.webp',
  },
  'backiee-7': {
    image: '/wallpaper/picture/backiee-7.webp',
    preview: '/wallpaper/picture-preview/backiee-7.webp',
  },
  'backiee-8': {
    image: '/wallpaper/picture/backiee-8.webp',
    preview: '/wallpaper/picture-preview/backiee-8.webp',
  },
  'backiee-9': {
    image: '/wallpaper/picture/backiee-9.webp',
    preview: '/wallpaper/picture-preview/backiee-9.webp',
  },
  mp_teal: {
    image: '/wallpaper/picture/mp_teal.webp',
    preview: '/wallpaper/picture-preview/mp_teal.webp',
  },
  ms: {
    image: '/wallpaper/picture/ms.webp',
    preview: '/wallpaper/picture-preview/ms.webp',
  },
  'openscreen-wallpaper13': {
    image: '/wallpaper/picture/openscreen-wallpaper13.webp',
    preview: '/wallpaper/picture-preview/openscreen-wallpaper13.webp',
  },
  'openscreen-wallpaper14': {
    image: '/wallpaper/picture/openscreen-wallpaper14.webp',
    preview: '/wallpaper/picture-preview/openscreen-wallpaper14.webp',
  },
  'openscreen-wallpaper18': {
    image: '/wallpaper/picture/openscreen-wallpaper18.webp',
    preview: '/wallpaper/picture-preview/openscreen-wallpaper18.webp',
  },
  'recordly-luisdelrio': {
    image: '/wallpaper/picture/recordly-luisdelrio.webp',
    preview: '/wallpaper/picture-preview/recordly-luisdelrio.webp',
  },
} satisfies Record<string, TWallpaper>

export const WALLPAPER_PATTERN = {
  '01': {
    id: '01',
    image: '/wallpaper/pattern/01.png',
    preview: '/wallpaper/pattern/01.png',
  },
  '02': {
    id: '02',
    image: '/wallpaper/pattern/02.png',
    preview: '/wallpaper/pattern/02.png',
  },
  '03': {
    id: '03',
    image: '/wallpaper/pattern/03.png',
    preview: '/wallpaper/pattern/03.png',
  },
  '04': {
    id: '04',
    image: '/wallpaper/pattern/04.png',
    preview: '/wallpaper/pattern/04.png',
  },
  '05': {
    id: '05',
    image: '/wallpaper/pattern/05.png',
    preview: '/wallpaper/pattern/05.png',
  },
  '06': {
    id: '06',
    image: '/wallpaper/pattern/06.png',
    preview: '/wallpaper/pattern/06.png',
  },
  '07': {
    id: '07',
    image: '/wallpaper/pattern/07.png',
    preview: '/wallpaper/pattern/07.png',
  },
  '08': {
    id: '08',
    image: '/wallpaper/pattern/08.png',
    preview: '/wallpaper/pattern/08.png',
  },
  '09': {
    id: '09',
    image: '/wallpaper/pattern/09.png',
    preview: '/wallpaper/pattern/09.png',
  },
  '10': {
    id: '10',
    image: '/wallpaper/pattern/10.png',
    preview: '/wallpaper/pattern/10.png',
  },
  '11': {
    id: '11',
    image: '/wallpaper/pattern/11.png',
    preview: '/wallpaper/pattern/11.png',
  },
  '12': {
    id: '12',
    image: '/wallpaper/pattern/12.png',
    preview: '/wallpaper/pattern/12.png',
  },
  '13': {
    id: '13',
    image: '/wallpaper/pattern/13.png',
    preview: '/wallpaper/pattern/13.png',
  },
  '14': {
    id: '14',
    image: '/wallpaper/pattern/14.png',
    preview: '/wallpaper/pattern/14.png',
  },
  '15': {
    id: '15',
    image: '/wallpaper/pattern/15.png',
    preview: '/wallpaper/pattern/15.png',
  },
  '16': {
    id: '16',
    image: '/wallpaper/pattern/16.png',
    preview: '/wallpaper/pattern/16.png',
  },
  '17': {
    id: '17',
    image: '/wallpaper/pattern/17.png',
    preview: '/wallpaper/pattern/17.png',
  },
  '18': {
    id: '18',
    image: '/wallpaper/pattern/18.png',
    preview: '/wallpaper/pattern/18.png',
  },
  '19': {
    id: '19',
    image: '/wallpaper/pattern/19.png',
    preview: '/wallpaper/pattern/19.png',
  },
  '20': {
    id: '20',
    image: '/wallpaper/pattern/20.png',
    preview: '/wallpaper/pattern/20.png',
  },
  '21': {
    id: '21',
    image: '/wallpaper/pattern/21.png',
    preview: '/wallpaper/pattern/21.png',
  },
  '22': {
    id: '22',
    image: '/wallpaper/pattern/22.png',
    preview: '/wallpaper/pattern/22.png',
  },
  '23': {
    id: '23',
    image: '/wallpaper/pattern/23.png',
    preview: '/wallpaper/pattern/23.png',
  },
  '24': {
    id: '24',
    image: '/wallpaper/pattern/24.png',
    preview: '/wallpaper/pattern/24.png',
  },
  '25': {
    id: '25',
    image: '/wallpaper/pattern/25.png',
    preview: '/wallpaper/pattern/25.png',
  },
  '26': {
    id: '26',
    image: '/wallpaper/pattern/26.png',
    preview: '/wallpaper/pattern/26.png',
  },
  '27': {
    id: '27',
    image: '/wallpaper/pattern/27.png',
    preview: '/wallpaper/pattern/27.png',
  },
  '28': {
    id: '28',
    image: '/wallpaper/pattern/28.png',
    preview: '/wallpaper/pattern/28.png',
  },
  '29': {
    id: '29',
    image: '/wallpaper/pattern/29.png',
    preview: '/wallpaper/pattern/29.png',
  },
  '30': {
    id: '30',
    image: '/wallpaper/pattern/30.png',
    preview: '/wallpaper/pattern/30.png',
  },
  '31': {
    id: '31',
    image: '/wallpaper/pattern/31.png',
    preview: '/wallpaper/pattern/31.png',
  },
  '32': {
    id: '32',
    image: '/wallpaper/pattern/32.png',
    preview: '/wallpaper/pattern/32.png',
  },
  '33': {
    id: '33',
    image: '/wallpaper/pattern/33.png',
    preview: '/wallpaper/pattern/33.png',
  },
} satisfies Record<string, TWallpaperPattern>
