import type { TWallpaper } from '~/spec'

/*
 * This file is generated by scripts/sync-wallpaper-assets.mjs.
 *
 * Mechanism:
 * - Every non-WebP image file placed in frontend/core/assets/wallpaper/picture
 *   is converted to WebP and included. Existing WebP files are treated as
 *   already compressed and are only size-checked.
 * - The wallpaper source key is the WebP file stem. If multiple source files
 *   share the same stem, the original extension is appended before conversion
 *   to avoid overwriting entries.
 * - Non-WebP source images are compressed into
 *   frontend/core/assets/wallpaper/picture and the script fails if a picture
 *   cannot be compressed under 500KB. Existing WebP pictures must already be
 *   under 500KB.
 * - Moving a file out of picture/ is the way to remove it from the picker.
 * - Each picture must have a matching file with the same filename in
 *   frontend/core/assets/wallpaper/picture-preview. The script creates missing
 *   previews before writing this manifest and fails if a preview cannot be
 *   compressed under 50KB.
 * - Picker cards must render preview, while the actual selected wallpaper renders image.
 *
 * Do not edit this file by hand; edit the assets folder and run yarn sync:wallpaper.
 */
export const PATTERN_WALLPAPER = {
  cartoon: {
    image: '/wallpaper/picture/cartoon.webp',
    preview: '/wallpaper/picture-preview/cartoon.webp',
  },
  co2: {
    image: '/wallpaper/picture/co2.webp',
    preview: '/wallpaper/picture-preview/co2.webp',
  },
  code: {
    image: '/wallpaper/picture/code.webp',
    preview: '/wallpaper/picture-preview/code.webp',
  },
  'country-1': {
    image: '/wallpaper/picture/country-1.webp',
    preview: '/wallpaper/picture-preview/country-1.webp',
  },
  curves: {
    image: '/wallpaper/picture/curves.webp',
    preview: '/wallpaper/picture-preview/curves.webp',
  },
  earth: {
    image: '/wallpaper/picture/earth.webp',
    preview: '/wallpaper/picture-preview/earth.webp',
  },
  elec: {
    image: '/wallpaper/picture/elec.webp',
    preview: '/wallpaper/picture-preview/elec.webp',
  },
  fishes: {
    image: '/wallpaper/picture/fishes.webp',
    preview: '/wallpaper/picture-preview/fishes.webp',
  },
  idian: {
    image: '/wallpaper/picture/idian.webp',
    preview: '/wallpaper/picture-preview/idian.webp',
  },
  istanbul: {
    image: '/wallpaper/picture/istanbul.webp',
    preview: '/wallpaper/picture-preview/istanbul.webp',
  },
  limones: {
    image: '/wallpaper/picture/limones.webp',
    preview: '/wallpaper/picture-preview/limones.webp',
  },
  mp_teal: {
    image: '/wallpaper/picture/mp_teal.webp',
    preview: '/wallpaper/picture-preview/mp_teal.webp',
  },
  ms: {
    image: '/wallpaper/picture/ms.webp',
    preview: '/wallpaper/picture-preview/ms.webp',
  },
  newspaper: {
    image: '/wallpaper/picture/newspaper.webp',
    preview: '/wallpaper/picture-preview/newspaper.webp',
  },
  'openscreen-wallpaper13': {
    image: '/wallpaper/picture/openscreen-wallpaper13.webp',
    preview: '/wallpaper/picture-preview/openscreen-wallpaper13.webp',
  },
  'openscreen-wallpaper14': {
    image: '/wallpaper/picture/openscreen-wallpaper14.webp',
    preview: '/wallpaper/picture-preview/openscreen-wallpaper14.webp',
  },
  'openscreen-wallpaper18': {
    image: '/wallpaper/picture/openscreen-wallpaper18.webp',
    preview: '/wallpaper/picture-preview/openscreen-wallpaper18.webp',
  },
  plane: {
    image: '/wallpaper/picture/plane.webp',
    preview: '/wallpaper/picture-preview/plane.webp',
  },
  rainbow: {
    image: '/wallpaper/picture/rainbow.webp',
    preview: '/wallpaper/picture-preview/rainbow.webp',
  },
  'recordly-luisdelrio': {
    image: '/wallpaper/picture/recordly-luisdelrio.webp',
    preview: '/wallpaper/picture-preview/recordly-luisdelrio.webp',
  },
  'recordly-midnight-8': {
    image: '/wallpaper/picture/recordly-midnight-8.webp',
    preview: '/wallpaper/picture-preview/recordly-midnight-8.webp',
  },
  'recordly-wallpaper13': {
    image: '/wallpaper/picture/recordly-wallpaper13.webp',
    preview: '/wallpaper/picture-preview/recordly-wallpaper13.webp',
  },
} satisfies Record<string, TWallpaper>
