name: Backend unit tests
on:
  push:
    paths:
      - "backend/main/**" # only trigger when this dir changes

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/main

    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          elixir-version: "1.19.5"

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: backend/main/deps
          key: ${{ runner.OS }}-otp26-elixir19-mix-${{ hashFiles('**/mix.lock', '**/mix.exs') }}
          restore-keys: |
            ${{ runner.OS }}-otp26-elixir19-mix-

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: backend/main/_build
          key: ${{ runner.OS }}-otp26-elixir19-build-${{ hashFiles('**/mix.lock', '**/mix.exs') }}
          restore-keys: |
            ${{ runner.OS }}-otp26-elixir19-build-

      - name: Install dependencies
        run: mix deps.get

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: backend/main
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: groupher_server_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          elixir-version: "1.19.5"

      - name: Restore cached deps
        uses: actions/cache@v3
        with:
          path: backend/main/deps
          key: ${{ runner.OS }}-otp26-elixir19-mix-${{ hashFiles('**/mix.lock', '**/mix.exs') }}
          restore-keys: |
            ${{ runner.OS }}-otp26-elixir19-mix-

      - name: Restore cached build
        uses: actions/cache@v3
        with:
          path: backend/main/_build
          key: ${{ runner.OS }}-otp26-elixir19-build-${{ hashFiles('**/mix.lock', '**/mix.exs') }}
          restore-keys: |
            ${{ runner.OS }}-otp26-elixir19-build-

      - name: Ensure dependencies are synced
        run: mix deps.get

      - name: Run tests
        run: mix test --exclude skip_ci --max-cases 8 --max-failures 1
