name: Build frontend dash

on:
  pull_request:
    paths:
      - 'frontend/dash/**'
      - 'frontend/core/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  push:
    branches:
      - dev
    paths:
      - 'frontend/dash/**'
      - 'frontend/core/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  build:
    name: Build dash
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - uses: pnpm/setup@v1
        with:
          install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build:prod:dash
