name: Build backend gateway

on:
  push:
    paths:
      - 'infra/gateway/**'
      - 'package.json'
      - 'yarn.lock'
      - 'Makefile'
  pull_request:
    paths:
      - 'infra/gateway/**'
      - 'package.json'
      - 'yarn.lock'
      - 'Makefile'

jobs:
  build:
    name: Build gateway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'groupher/groupher'
          path: './'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.0'

      - name: Install Yarn Dependencies
        run: |
          corepack enable
          yarn install --immutable

      - name: Run Gateway Tests
        run: make be.gateway.test

      - name: Build Project
        run: make be.gateway.build
