name: Build frontend gateway

on:
  push:
    paths:
      - "frontend/gateway/**" # only trigger when this dir changes
      - "!frontend/gateway/vercel.json"
  pull_request:
    paths:
      - "frontend/gateway/**"
      - "!frontend/gateway/vercel.json"

jobs:
  build:
    name: Build gateway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: "groupher/groupher"
          path: "./"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.13.0"

      - name: Install Yarn Dependencies
        run: |
          corepack enable
          yarn install --immutable

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      # - name: Run Biome for gateway
      #   run: biome lint "$GITHUB_WORKSPACE/frontend-gateway/src/**/*.{ts,tsx}"

      - name: Run Gateway Tests
        run: make fe.test.gateway

      - name: Build Project
        run: yarn run build:prod:gateway
