name: Build frontend main

on:
  push:
    paths:
      - "frontend/main/**" # only trigger when this dir changes
      - "!frontend/main/vercel.json"

jobs:
  build:
    name: Build main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: "groupher/groupher"
          path: "./"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.13.0"
          cache: "yarn"

      - name: Install Yarn Dependencies
        run: |
          corepack enable
          yarn install --immutable

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      # ... (其他步骤，例如 Biome lint)

      - name: Build Project
        run: yarn run build:prod:main
