name: Build frontend landing

on:
  push:
    paths:
      - "frontend/landing/**" # only trigger when this dir changes
      - "!frontend/landing/vercel.json"

jobs:
  build:
    name: Build landing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: "groupher/groupher"
          path: "./"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.13.0"

      - name: Install Yarn Dependencies
        run: |
          corepack enable
          yarn install --immutable

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      # - name: Run Biome for landing
      #   run: biome lint "$GITHUB_WORKSPACE/frontend-landing/src/**/*.{ts,tsx}"

      - name: Build Project
        run: yarn run build:prod:landing
